# Generated by Django 6.0.8 — Lineage item XML catalog tests

from pathlib import Path

import pytest

from apps.server.infrastructure.lineage.item_catalog import LineageItemCatalog, item_display_name

SAMPLE = """
<list>
  <weapon id="1" name="Short Sword">
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.weapon_small_sword_i00"/>
    <set name="type" value="SWORD"/>
    <equip><slot id="RIGHT_HAND"/></equip>
  </weapon>
  <etcitem id="57" name="Adena">
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_adena_i00"/>
    <set name="tradeable" value="true"/>
    <set name="type" value="MONEY"/>
  </etcitem>
  <armor id="114" name="Squire&apos;s Shirt">
    <set name="crystal_type" value="NONE"/>
    <set name="tradeable" value="false"/>
    <set name="type" value="LIGHT"/>
    <equip><slot id="CHEST"/></equip>
  </armor>
</list>
"""


def test_parses_xml_catalog(tmp_path: Path):
    (tmp_path / "0-99.xml").write_text(SAMPLE, encoding="utf-8")
    catalog = LineageItemCatalog.load(tmp_path)
    sword = catalog.get(1)
    assert sword is not None
    assert sword.name == "Short Sword"
    assert sword.category == "WEAPON"
    assert sword.tradeable is True
    adena = catalog.get(57)
    assert adena is not None
    assert adena.name == "Adena"
    assert adena.category == "COMUM"
    assert catalog.is_tradeable(57) is True
    shirt = catalog.get(114)
    assert shirt is not None
    assert shirt.name == "Squire's Shirt"
    assert shirt.category == "ARMOR"
    assert catalog.is_tradeable(114) is False
    assert catalog.is_tradeable(999999) is False


def test_search_by_id_and_name(tmp_path: Path):
    (tmp_path / "0-99.xml").write_text(SAMPLE, encoding="utf-8")
    catalog = LineageItemCatalog.load(tmp_path)
    assert catalog.search("57")[0].name == "Adena"
    assert catalog.search("short")[0].id == 1


def test_real_xml_has_adena():
    catalog = LineageItemCatalog.load()
    item = catalog.get(57)
    if item is None:
        pytest.skip("XML do catálogo L2 não está presente")
    assert item.name == "Adena"
    assert item.tradeable is True
    assert catalog.is_tradeable(57) is True
    assert item_display_name(57) == "Adena"
    assert item_display_name(99999999) == "Item 99999999"
