# Generated by Django 6.0.8 on 2026-08-31 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=100)),
                ('data_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Log de webhook',
                'verbose_name_plural': 'Logs de webhook',
            },
        ),
        migrations.AlterModelOptions(
            name='pedidopagamento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido de pagamento', 'verbose_name_plural': 'Pedidos de pagamento'},
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='bonus_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='total_credited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidopagamento',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidopagamento',
            name='method',
            field=models.CharField(default='mock', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidopagamento',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
