# Generated by Django 6.0.8 on 2026-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_webhooklog_alter_pedidopagamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopagamento',
            name='client_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar')], default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='gateway_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='package_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidopagamento',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
