# Generated by Django 6.0.8 on 2026-08-31 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clanprofile',
            name='clan_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clanprofile',
            name='focus',
            field=models.CharField(default='MIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='clanprofile',
            name='min_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clanprofile',
            name='motd',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('char_name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clans.clanprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição de clã',
                'verbose_name_plural': 'Inscrições de clã',
                'unique_together': {('clan', 'user')},
            },
        ),
    ]
