ACHIEVEMENTS: list[tuple[str, str, str]] = [
    ("primeiro_login", "Primeiro Login", "Realizou o primeiro login no sistema"),
    ("avatar_editado", "Avatar Editado", "Editou seu avatar pela primeira vez"),
    ("email_verificado", "Email Verificado", "Verificou seu e-mail"),
    ("2fa_ativado", "2FA Ativado", "Ativou a autenticação de dois fatores (2FA)"),
    ("primeira_compra", "Primeira Compra", "Realizou sua primeira compra na loja"),
    ("comprador_frequente", "Comprador Frequente", "Realizou 5 ou mais compras na loja"),
    ("comprador_vip", "Comprador VIP", "Realizou 15 ou mais compras na loja"),
    ("primeiro_lance", "Primeiro Lance", "Realizou seu primeiro lance em um leilão"),
    ("50_lances", "Lanceador Experiente", "Realizou 50 lances em leilões"),
    ("lanceador_profissional", "Lanceador Profissional", "Realizou 100 ou mais lances"),
    ("lanceador_mestre", "Lanceador Mestre", "Realizou 200 ou mais lances"),
    ("10_leiloes", "10 Leilões", "Criou 10 leilões no sistema"),
    ("leiloeiro_profissional", "Leiloeiro Profissional", "Criou 25 ou mais leilões"),
    ("leiloeiro_mestre", "Leiloeiro Mestre", "Criou 50 ou mais leilões"),
    ("primeiro_vencedor_leilao", "Vencedor de Leilão", "Venceu seu primeiro leilão"),
    ("vencedor_serie", "Vencedor em Série", "Venceu 3 ou mais leilões"),
    ("vencedor_mestre", "Vencedor Mestre", "Venceu 10 ou mais leilões"),
    ("primeiro_pedido_pagamento", "Primeira Contribuição", "Iniciou sua primeira contribuição para o servidor"),
    ("primeiro_pagamento_concluido", "Patrocinador Oficial", "Realizou seu primeiro apoio financeiro ao servidor"),
    ("patrocinador_ouro", "Patrocinador Ouro", "Realizou 5 ou mais pagamentos aprovados"),
    ("patrocinador_diamante", "Patrocinador Diamante", "Realizou 10 ou mais pagamentos aprovados"),
    ("primeira_transferencia_para_jogador", "Aliado Generoso", "Enviou moedas para outro jogador pela primeira vez"),
    ("benfeitor_comunitario", "Benfeitor Comunitário", "Realizou 10 ou mais transferências para outros jogadores"),
    ("100_transacoes", "Mestre das Transações", "Realizou 100 transações na carteira"),
    ("250_transacoes", "Mestre das Transações", "Realizou 250 transações na carteira"),
    ("500_transacoes", "Expert das Transações", "Realizou 500 transações na carteira"),
    ("primeiro_bonus", "Bônus Recebido", "Recebeu seu primeiro bônus de compra"),
    ("bonus_mestre", "Mestre dos Bônus", "Recebeu 10 ou mais bônus"),
    ("bonus_expert", "Expert dos Bônus", "Recebeu 25 ou mais bônus"),
    ("primeira_retirada_item", "Caçador de Tesouros", "Retirou seu primeiro item do jogo para o inventário online"),
    ("primeira_insercao_item", "De Volta à Batalha", "Inseriu um item do inventário online no servidor pela primeira vez"),
    ("primeira_troca_itens", "Comerciante Astuto", "Realizou sua primeira troca de item entre personagens"),
    ("colecionador_itens", "Colecionador de Itens", "Possui 10 ou mais itens no inventário"),
    ("mestre_inventario", "Mestre do Inventário", "Possui 50 ou mais itens no inventário"),
    ("trocador_incansavel", "Trocador Incansável", "Realizou 10 ou mais trocas de itens"),
    ("nivel_10", "Veterano Iniciante", "Alcançou o nível 10 no sistema"),
    ("nivel_25", "Veterano Avançado", "Alcançou o nível 25 no sistema"),
    ("nivel_50", "Veterano Experiente", "Alcançou o nível 50 no sistema"),
    ("nivel_75", "Veterano Mestre", "Alcançou o nível 75 no sistema"),
    ("nivel_100", "Lenda do Sistema", "Alcançou o nível 100 no sistema"),
    ("1000_xp", "Mestre da Experiência", "Acumulou 1000 pontos de experiência"),
    ("5000_xp", "Mestre da Experiência", "Acumulou 5000 pontos de experiência"),
    ("10000_xp", "Lenda da Experiência", "Acumulou 10000 pontos de experiência"),
    ("primeiro_spin", "Primeiro Giro", "Realizou o primeiro giro na roleta"),
    ("10_spins", "10 Giros", "Realizou 10 giros na roleta"),
    ("50_spins", "50 Giros", "Realizou 50 giros na roleta"),
    ("100_spins", "100 Giros", "Realizou 100 giros na roleta"),
    ("primeiro_premio_roleta", "Primeiro Prêmio", "Ganhou o primeiro prêmio na roleta"),
    ("primeira_caixa_aberta", "Primeira Caixa", "Abriu a primeira caixa"),
    ("10_caixas_abertas", "10 Caixas Abertas", "Abriu 10 caixas"),
    ("50_caixas_abertas", "50 Caixas Abertas", "Abriu 50 caixas"),
    ("100_caixas_abertas", "100 Caixas Abertas", "Abriu 100 caixas"),
    ("item_epico_caixa", "Item Épico", "Obteve um item épico de uma caixa"),
    ("item_lendario_caixa", "Item Lendário", "Obteve um item lendário de uma caixa"),
    ("primeira_jogada_slot", "Primeira Jogada Slot", "Realizou a primeira jogada na Slot Machine"),
    ("10_jogadas_slot", "10 Jogadas Slot", "Realizou 10 jogadas na Slot Machine"),
    ("50_jogadas_slot", "50 Jogadas Slot", "Realizou 50 jogadas na Slot Machine"),
    ("100_jogadas_slot", "100 Jogadas Slot", "Realizou 100 jogadas na Slot Machine"),
    ("primeiro_jackpot", "Primeiro Jackpot", "Ganhou o primeiro jackpot na Slot Machine"),
    ("jackpot_mestre", "Mestre do Jackpot", "Ganhou 3 ou mais jackpots"),
    ("primeira_jogada_dice", "Primeira Jogada Dice", "Realizou a primeira jogada no Dice Game"),
    ("10_jogadas_dice", "10 Jogadas Dice", "Realizou 10 jogadas no Dice Game"),
    ("50_jogadas_dice", "50 Jogadas Dice", "Realizou 50 jogadas no Dice Game"),
    ("primeira_vitoria_dice", "Primeira Vitória Dice", "Ganhou a primeira aposta no Dice Game"),
    ("10_vitorias_dice", "10 Vitórias Dice", "Ganhou 10 apostas no Dice Game"),
    ("50_vitorias_dice", "50 Vitórias Dice", "Ganhou 50 apostas no Dice Game"),
    ("primeira_pescaria", "Primeira Pescaria", "Realizou a primeira pescaria"),
    ("10_peixes_capturados", "10 Peixes Capturados", "Capturou 10 peixes"),
    ("50_peixes_capturados", "50 Peixes Capturados", "Capturou 50 peixes"),
    ("100_peixes_capturados", "100 Peixes Capturados", "Capturou 100 peixes"),
    ("peixe_raro", "Peixe Raro", "Capturou um peixe raro"),
    ("peixe_epico", "Peixe Épico", "Capturou um peixe épico"),
    ("peixe_lendario", "Peixe Lendário", "Capturou um peixe lendário"),
    ("vara_nivel_5", "Vara Nível 5", "Alcançou o nível 5 na vara de pesca"),
    ("vara_nivel_10", "Vara Nível 10", "Alcançou o nível 10 na vara de pesca"),
    ("vara_nivel_20", "Vara Nível 20", "Alcançou o nível 20 na vara de pesca"),
    ("primeiro_battle_pass", "Primeiro Battle Pass", "Participou do primeiro Battle Pass"),
    ("battle_pass_nivel_10", "Battle Pass Nível 10", "Alcançou o nível 10 no Battle Pass"),
    ("battle_pass_nivel_25", "Battle Pass Nível 25", "Alcançou o nível 25 no Battle Pass"),
    ("battle_pass_nivel_50", "Battle Pass Nível 50", "Alcançou o nível 50 no Battle Pass"),
    ("battle_pass_premium", "Battle Pass Premium", "Comprou o Battle Pass Premium"),
    ("primeiro_daily_bonus", "Primeiro Daily Bonus", "Recebeu o primeiro Daily Bonus"),
    ("daily_bonus_7dias", "Daily Bonus 7 Dias", "Recebeu Daily Bonus por 7 dias"),
    ("daily_bonus_30dias", "Daily Bonus 30 Dias", "Recebeu Daily Bonus por 30 dias"),
    ("daily_bonus_100dias", "Daily Bonus 100 Dias", "Recebeu Daily Bonus por 100 dias"),
    ("primeira_transacao_marketplace", "Primeira Transação", "Realizou a primeira transação no Marketplace"),
    ("5_transacoes_marketplace", "5 Transações", "Realizou 5 ou mais transações no Marketplace"),
    ("10_transacoes_marketplace", "10 Transações", "Realizou 10 ou mais transações no Marketplace"),
    ("primeira_transferencia_personagem", "Primeira Transferência", "Realizou a primeira transferência de personagem"),
    ("primeira_bag", "Primeira Bag", "Obteve a primeira bag"),
]
