from .jazzmin_icons import JAZZMIN_ICONS_PDL


JAZZMIN_SETTINGS_PDL = {
    "site_title": "PDL PRO",
    "site_header": "PDL PRO Admin",
    "site_brand": "PDL PRO",
    "welcome_sign": "Acesso ao painel administrativo",
    "copyright": "PDL PRO",
    "site_logo": "pdl_admin/img/logo.png",
    "login_logo": "pdl_admin/img/logo.png",
    "login_logo_dark": "pdl_admin/img/logo.png",
    "site_logo_classes": "pdl-admin-logo",
    "site_icon": "pdl_admin/img/favicon-32x32.png",
    "custom_css": "pdl_admin/css/admin.css",
    "custom_js": "pdl_admin/js/forms.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "navigation_expanded": False,
    "search_model": [
        "accounts.User",
        "wallet.Wallet",
        "shop.ShopItem",
        "content.News",
    ],
    "order_with_respect_to": [
        "accounts",
        "server",
        "wallet",
        "payment",
        "shop",
        "inventory",
        "content",
        "communication",
        "games",
        "auction",
        "marketplace",
        "staff",
    ],
    "icons": JAZZMIN_ICONS_PDL,
}

JAZZMIN_UI_TWEAKS_PDL = {
    "theme": "darkly",
    "default_theme_mode": "dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-dark",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
