MIDDLEWARE_PDL = [
    "common.middleware.RequestIdMiddleware",
    "common.middleware.ApiErrorContractMiddleware",
    "common.middleware.DependencyInjectionMiddleware",
    "apps.server.presentation.catalog_middleware.ItemCatalogScopeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.programs.middleware.ResourceGateMiddleware",
]
