# Generated by Django 6.0.8 on 2026-08-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterlisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anúncio de personagem', 'verbose_name_plural': 'Anúncios de personagem'},
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='char_class',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='char_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='new_account',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='old_account',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='characterlisting',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterlisting',
            name='status',
            field=models.CharField(choices=[('for_sale', 'À venda'), ('sold', 'Vendido'), ('cancelled', 'Cancelado'), ('disputed', 'Em disputa')], default='for_sale', max_length=20),
        ),
        migrations.AddIndex(
            model_name='characterlisting',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_7bea2a_idx'),
        ),
        migrations.AddIndex(
            model_name='characterlisting',
            index=models.Index(fields=['char_id'], name='marketplace_char_id_e38fb4_idx'),
        ),
    ]
