# Generated by Django 6.0.8 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_characterlisting_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterlisting",
            name="bag_items",
            field=models.JSONField(blank=True, default=list, verbose_name="Itens da bag e warehouse"),
        ),
        migrations.AddField(
            model_name="characterlisting",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="Skills do personagem"),
        ),
    ]
