# Generated by Django 6.0.8 on 2026-08-31 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_chat_chatmessage_friendship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador público. Sempre UUID v4.",
                        unique=True,
                    ),
                ),
                (
                    "seq_id",
                    models.BigAutoField(
                        editable=False,
                        help_text="ID sequencial interno. Nunca expor via API.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.URLField(max_length=500)),
                ("auth", models.CharField(max_length=255)),
                ("p256dh", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição push",
                "verbose_name_plural": "Inscrições push",
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
