"""Catálogo dos micro-recursos do core e relações de herança.

As preferências dos filhos permanecem independentes; desativar um ancestral bloqueia
seus descendentes sem sobrescrever os valores salvos. Não contém dependências de framework.
"""

MICRO_RESOURCE_NAMES = {
    "accounts-link": "Vincular conta existente",
    "accounts-create-character": "Criar personagem",
    "progress-achievements": "Conquistas",
    "shop-checkout": "Finalizar compras",
    "shop-packages": "Pacotes da loja",
    "shop-history": "Histórico de compras",
    "wallet-purchase": "Comprar moedas",
    "wallet-transfer": "Transferir saldo",
    "wallet-game-exchange": "Câmbio com o jogo",
    "wallet-history": "Histórico financeiro",
    "inventory-withdraw": "Retirar itens do jogo",
    "inventory-deposit": "Enviar itens ao jogo",
    "inventory-trade": "Transferir itens entre personagens",
    "inventory-bag-transfer": "Mover itens da bag para o baú",
    "marketplace-sell": "Anunciar vendas",
    "marketplace-buy": "Comprar anúncios",
    "auction-create": "Criar leilões",
    "auction-bid": "Dar lances",
    "games-roulette": "Roda da Fortuna",
    "games-boxes": "Baús",
    "games-boxes-buy": "Comprar e reiniciar baús",
    "games-boxes-open": "Abrir baús",
    "games-dice": "Dados",
    "games-slots": "Slot Machine",
    "games-economy": "Arena e encantamento",
    "games-fight": "Combater monstros",
    "games-enchant": "Encantar arma",
    "games-buy-tokens": "Comprar fichas",
    "games-statistics": "Estatísticas dos jogos",
    "battle-pass-premium": "Comprar passe premium",
    "battle-pass-claim": "Resgatar recompensas de nível",
    "battle-pass-quests": "Resgatar missões",
    "battle-pass-exchanges": "Trocas do passe",
    "battle-pass-milestones": "Resgatar marcos",
    "battle-pass-auto-claim": "Resgate automático",
    "daily-bonus-claim": "Resgatar bônus diário",
    "fishing-cast": "Lançar a vara",
    "fishing-buy-bait": "Comprar iscas",
    "hunt-claim": "Resgatar missões da caça",
    "accounts-register": "Criar conta de jogo",
    "accounts-link-credentials": "Vincular por login e senha",
    "accounts-link-email": "Vincular por e-mail",
    "accounts-buy-slots": "Comprar vagas de contas",
    "accounts-password": "Alterar senha da conta de jogo",
    "accounts-unlink": "Desvincular conta de jogo",
    "accounts-nickname": "Alterar nome do personagem",
    "accounts-sex": "Alterar gênero do personagem",
    "accounts-unstuck": "Destravar personagem",
    "accounts-teleport": "Teleportar personagem",
    "accounts-appearance": "Alterar aparência",
    "accounts-clear-karma": "Limpar karma",
    "accounts-clear-pk": "Limpar PK",
    "accounts-skills": "Consultar skills do personagem",
    "profile-edit": "Editar perfil e avatar",
    "progress-claim-rewards": "Resgatar prêmios da conta",
    "supporters-apply": "Candidatura e perfil de apoiador",
    "supporters-payout": "Solicitar saque de comissões",
    "notifications-push": "Notificações push",
    "support-create": "Abrir chamados",
    "support-reply": "Responder chamados",
    "support-status": "Encerrar e reabrir chamados",
    "help-chat": "Conversar com o assistente",
    "help-pet": "Cuidados do Denkynho",
    "help-wardrobe": "Armário do Denkynho",
    "news-detail": "Ler notícias completas",
    "wiki-detail": "Ler páginas da Wiki",
    "faq-panel": "FAQ no painel",
    "roadmap-detail": "Detalhes do roadmap",
    "rankings-pvp": "Ranking PvP",
    "rankings-pk": "Ranking PK",
    "rankings-adena": "Ranking Adena",
    "rankings-clans": "Ranking de clãs",
    "rankings-level": "Ranking de nível",
    "rankings-online": "Ranking de tempo online",
    "rankings-olympiad": "Olimpíadas",
    "rankings-grandboss": "Grand Bosses",
    "rankings-siege": "Cerco aos castelos",
    "rankings-search": "Buscar personagens",
}

RESOURCE_PARENTS = {
    "accounts-link": "accounts",
    "accounts-create-character": "accounts",
    "progress-achievements": "progress",
    "shop-checkout": "shop",
    "shop-packages": "shop",
    "shop-history": "shop",
    "wallet-purchase": "wallet",
    "wallet-transfer": "wallet",
    "wallet-game-exchange": "wallet",
    "wallet-history": "wallet",
    "inventory-withdraw": "inventory",
    "inventory-deposit": "inventory",
    "inventory-trade": "inventory",
    "inventory-bag-transfer": "inventory",
    "marketplace-sell": "marketplace",
    "marketplace-buy": "marketplace",
    "auction-create": "auction",
    "auction-bid": "auction",
    "games-roulette": "games",
    "games-boxes": "games",
    "games-boxes-buy": "games-boxes",
    "games-boxes-open": "games-boxes",
    "games-dice": "games",
    "games-slots": "games",
    "games-economy": "games",
    "games-fight": "games-economy",
    "games-enchant": "games-economy",
    "games-buy-tokens": "games",
    "games-statistics": "games",
    "battle-pass-premium": "battle-pass",
    "battle-pass-claim": "battle-pass",
    "battle-pass-quests": "battle-pass",
    "battle-pass-exchanges": "battle-pass",
    "battle-pass-milestones": "battle-pass",
    "battle-pass-auto-claim": "battle-pass",
    "daily-bonus-claim": "daily-bonus",
    "fishing-cast": "fishing",
    "fishing-buy-bait": "fishing",
    "hunt-claim": "hunt",
    "accounts-register": "accounts",
    "accounts-link-credentials": "accounts-link",
    "accounts-link-email": "accounts-link",
    "accounts-buy-slots": "accounts",
    "accounts-password": "accounts",
    "accounts-unlink": "accounts",
    "accounts-nickname": "accounts",
    "accounts-sex": "accounts",
    "accounts-unstuck": "accounts",
    "accounts-teleport": "accounts",
    "accounts-appearance": "accounts",
    "accounts-clear-karma": "accounts",
    "accounts-clear-pk": "accounts",
    "accounts-skills": "accounts",
    "profile-edit": "profile",
    "progress-claim-rewards": "progress",
    "supporters-apply": "supporters",
    "supporters-payout": "supporters",
    "notifications-push": "notifications",
    "support-create": "support",
    "support-reply": "support",
    "support-status": "support",
    "help-chat": "help",
    "help-pet": "help",
    "help-wardrobe": "help-pet",
    "news-detail": "news",
    "wiki-detail": "wiki",
    "faq-panel": "faq",
    "roadmap-detail": "roadmap",
    "rankings-pvp": "rankings",
    "rankings-pk": "rankings",
    "rankings-adena": "rankings",
    "rankings-clans": "rankings",
    "rankings-level": "rankings",
    "rankings-online": "rankings",
    "rankings-olympiad": "rankings",
    "rankings-grandboss": "rankings",
    "rankings-siege": "rankings",
    "rankings-search": "rankings",
}


def resource_ancestors(code: str) -> list[str]:
    """Retorna o recurso e sua cadeia de pais para consultar a ativação efetiva."""
    ancestors = [code]
    while parent := RESOURCE_PARENTS.get(ancestors[-1]):
        if parent in ancestors:
            raise ValueError("Ciclo no catálogo de recursos")
        ancestors.append(parent)
    return ancestors
