# Generated by Django 5.2 for PDL PRO.
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ThemePackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identificador público. Sempre UUID v4.", unique=True)),
                ("seq_id", models.BigAutoField(editable=False, help_text="ID sequencial interno. Nunca expor via API.", primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=32)),
                ("author", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("manifest", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("storage_path", models.CharField(max_length=180, unique=True)),
                ("entrypoint", models.CharField(max_length=180)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("installed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="installed_themes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Tema", "verbose_name_plural": "Temas", "ordering": ["name", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="themepackage",
            constraint=models.UniqueConstraint(fields=("slug", "version"), name="themes_unique_slug_version"),
        ),
        migrations.AddConstraint(
            model_name="themepackage",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="themes_single_active_package"),
        ),
    ]
