# Generated by Django 6.0.8 on 2026-09-25 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auditlog_actor_auditlog_ip_address_auditlog_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretRotationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('rotate_secret_key', 'Rotacionar SECRET_KEY'), ('prune_secret_fallbacks', 'Remover fallbacks da SECRET_KEY'), ('rotate_data_encryption_key', 'Rotacionar cifra de dados'), ('prune_data_fallbacks', 'Remover fallbacks da cifra de dados'), ('rotate_backup_encryption_key', 'Rotacionar chave de backup'), ('reencrypt_sealed_data', 'Regravar dados cifrados'), ('revoke_all_sessions', 'Revogar todas as sessões JWT')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('applied', 'Aplicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(default='panel', max_length=32)),
                ('confirmation_domain', models.CharField(blank=True, default='', max_length=120)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('restart_required', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_rotation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job de rotação de segredo',
                'verbose_name_plural': 'Jobs de rotação de segredos',
                'ordering': ('-created_at',),
            },
        ),
    ]
