# Generated by Django 6.0.8 on 2026-09-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_integration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='oauth_blob',
            field=models.TextField(blank=True, default=''),
        ),
    ]
