# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_integration_oauth_blob"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsettings",
            name="denkynho_blob",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="observability_blob",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="storage_blob",
            field=models.TextField(blank=True, default=""),
        ),
    ]
