# Generated by Django 6.0.8 on 2026-09-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_calendarevent_wikipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('getting_started', 'Primeiros passos'), ('account_security', 'Conta e segurança'), ('game_accounts', 'Contas e personagens'), ('economy', 'Carteira e inventário'), ('commerce', 'Loja e comércio'), ('games_rewards', 'Jogos e recompensas'), ('community', 'Conteúdo e comunidade'), ('support', 'Ajuda e atendimento')], default='getting_started', max_length=40),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Termos alternativos separados por vírgulas usados para localizar esta orientação.', max_length=500),
        ),
        migrations.AddField(
            model_name='faq',
            name='short_answer',
            field=models.CharField(blank=True, help_text='Resposta rápida exibida primeiro pelo assistente; a resposta completa traz os detalhes.', max_length=400),
        ),
    ]
