from uuid import UUID

from django.db import migrations


# IDs fixos tornam a carga repetível e permitem desfazer somente os artigos deste catálogo.
FAQ_ITEMS = [
    ("c0100000-0000-4000-8000-000000000001", "getting_started", "O que é o PDL 2.0?", "O PDL 2.0 é o portal que reúne sua conta e os serviços da comunidade.", "No PDL 2.0 você encontra informações públicas do servidor e, ao entrar, gerencia perfil, segurança, contas do jogo, personagens, inventário, carteira, comércio, jogos, recompensas, avisos e atendimento. Alguns módulos podem ser desativados pela administração.", "portal,painel,o que é,recursos"),
    ("c0100000-0000-4000-8000-000000000002", "getting_started", "Como começo a usar o PDL?", "Crie sua conta do portal, confirme o e-mail e entre no painel.", "Use a página Criar conta, informe os dados solicitados e confirme o endereço de e-mail. Depois do login, abra Conta L2 para criar ou vincular uma conta do jogo. Os downloads, a wiki, as notícias, o calendário e o status do servidor ficam disponíveis nas páginas públicas.", "cadastro,registrar,começar,primeiros passos"),
    ("c0100000-0000-4000-8000-000000000003", "getting_started", "Onde vejo o status, os downloads e as informações do servidor?", "Essas informações ficam nas páginas públicas do PDL.", "Consulte Informações para o status e os dados publicados do servidor, Downloads para os arquivos oficiais, Wiki para guias, Calendário para eventos e Notícias para comunicados. Use apenas links publicados pelo próprio portal.", "online,offline,cliente,patch,download,informações"),
    ("c0100000-0000-4000-8000-000000000004", "getting_started", "Por que um recurso não aparece no meu menu?", "Alguns módulos podem estar temporariamente desativados pela administração.", "O PDL permite ativar ou desativar módulos como carteira, loja, inventário, marketplace, leilão, jogos, recompensas, apoiadores e roadmap. Quando um módulo está desativado, o menu e sua API ficam bloqueados, mas os dados existentes não são apagados. Consulte os avisos ou o atendimento se precisar confirmar a disponibilidade.", "sumiu,indisponível,desativado,bloqueado,menu"),
    ("c0100000-0000-4000-8000-000000000005", "account_security", "Como recupero a senha do portal?", "Use Esqueci minha senha na tela de login.", "Abra Esqueci minha senha, informe o e-mail da conta e siga o link de recuperação recebido. O link e os códigos de acesso são pessoais. Se você não receber a mensagem, confira spam e lixo eletrônico antes de abrir um chamado.", "esqueci senha,redefinir senha,reset,login"),
    ("c0100000-0000-4000-8000-000000000006", "account_security", "Como confirmo meu endereço de e-mail?", "Use o link enviado pelo PDL ou solicite uma nova confirmação.", "A confirmação associa o endereço à sua conta do portal. Abra o link recebido ou use a opção de reenviar a confirmação quando disponível. Confira se digitou o endereço corretamente e verifique spam e lixo eletrônico.", "verificar email,confirmação,email não chegou"),
    ("c0100000-0000-4000-8000-000000000007", "account_security", "Como protejo minha conta?", "Use uma senha exclusiva e ative 2FA ou uma passkey em Conta e segurança.", "Em Conta e segurança você pode gerenciar a autenticação em duas etapas e passkeys quando esses métodos estiverem disponíveis. Não compartilhe senha, código temporário, link de recuperação ou credencial do jogo. O atendimento nunca precisa desses segredos para analisar um chamado.", "2fa,passkey,segurança,código,autenticador"),
    ("c0100000-0000-4000-8000-000000000008", "account_security", "Posso entrar com uma conta social?", "O login social aparece quando um provedor foi habilitado no servidor.", "A tela de login informa os provedores sociais disponíveis. O acesso passa pelo provedor escolhido e volta ao PDL para concluir a sessão. Se a opção não aparecer, use o login normal ou outro método oferecido na tela.", "oauth,google,discord,login social,provedor"),
    ("c0100000-0000-4000-8000-000000000009", "account_security", "Onde altero meu perfil e avatar?", "Abra Meu perfil no painel.", "Em Meu perfil você consulta e altera os dados públicos permitidos da conta, incluindo nome de exibição e avatar quando disponíveis. Dados de login e métodos de proteção ficam em Conta e segurança.", "nome,avatar,foto,perfil,dados"),
    ("c0100000-0000-4000-8000-000000000010", "game_accounts", "Como crio uma conta do jogo?", "Abra Conta L2 e escolha a opção de cadastrar uma conta.", "A conta do portal e a conta L2 são registros diferentes. Entre no painel, abra Conta L2 e use Cadastrar conta. Informe um login disponível e os demais dados solicitados. Os limites e requisitos mostrados na tela são os válidos para o servidor.", "lineage,l2,game account,cadastrar conta,login do jogo"),
    ("c0100000-0000-4000-8000-000000000011", "game_accounts", "Como vinculo uma conta L2 que já existe?", "Use Vincular conta em Conta L2.", "Abra Conta L2 e escolha Vincular conta. O PDL oferece os métodos de comprovação habilitados, inclusive confirmação por e-mail quando configurada. A vinculação só deve ser feita pelo proprietário da conta do jogo.", "associar conta,link account,conta existente,vincular email"),
    ("c0100000-0000-4000-8000-000000000012", "game_accounts", "Como altero a senha da minha conta L2?", "Abra Conta L2 e use a ação de senha da conta vinculada.", "A alteração da senha do jogo é feita na área Conta L2 para uma conta que pertence ao usuário autenticado. Confirme os campos solicitados e guarde a nova senha em segurança. A senha do portal não é alterada por essa operação.", "senha lineage,senha l2,senha jogo"),
    ("c0100000-0000-4000-8000-000000000013", "game_accounts", "Onde vejo meus personagens?", "Os personagens aparecem nas contas vinculadas em Conta L2.", "Abra Conta L2 e selecione uma conta para consultar seus personagens. A página do personagem reúne os dados que a integração do servidor disponibiliza. Se uma alteração recente ainda não aparecer, atualize a consulta antes de abrir um chamado.", "char,boneco,personagem,personagens"),
    ("c0100000-0000-4000-8000-000000000014", "game_accounts", "Como uso os serviços de personagem?", "Abra o personagem e escolha o serviço disponível.", "O PDL pode oferecer mudança de apelido, mudança de sexo e destravamento. A tela informa disponibilidade, requisitos e custo antes da confirmação. A operação só é permitida em personagem pertencente a uma conta vinculada ao usuário.", "nick,nickname,sexo,destravar,unstuck,serviço"),
    ("c0100000-0000-4000-8000-000000000015", "economy", "Qual é a diferença entre carteira, bônus e fichas?", "São saldos com finalidades diferentes dentro do PDL.", "A carteira separa o saldo normal do saldo de bônus. Compras e regras promocionais podem tratar cada saldo de forma diferente. Fichas pertencem à economia dos jogos do painel. A tela de cada operação mostra qual saldo será usado; consulte o histórico para conferir os lançamentos.", "saldo,moedas,coin,bonus,tokens,fichas"),
    ("c0100000-0000-4000-8000-000000000016", "economy", "Como transfiro saldo para outro jogador?", "Use Transferir na Carteira e confirme o destinatário e o valor.", "A transferência usa o saldo permitido da carteira e registra a movimentação no histórico. Confira cuidadosamente o destinatário, o valor e o resumo antes de confirmar. A operação pode ser recusada por dados inválidos, saldo insuficiente ou limites configurados.", "enviar moedas,transferência,p2p,destinatário"),
    ("c0100000-0000-4000-8000-000000000017", "economy", "Como funciona o câmbio entre o painel e o jogo?", "Abra Carteira e acesse a área de câmbio com o jogo.", "O câmbio converte a moeda configurada entre a carteira do painel e o servidor de jogo. A tela apresenta direção, taxa, limites e resultado previsto antes da confirmação. Se uma operação ficar pendente após uma falha de comunicação, consulte o histórico e evite repetir com dados diferentes; o atendimento pode verificar o recibo.", "exchange,câmbio,adena,jogo,converter,pendente"),
    ("c0100000-0000-4000-8000-000000000018", "economy", "Como deposito ou retiro itens do inventário?", "Use Inventário para mover itens entre a bag do painel e um personagem elegível.", "O Inventário mostra a bag do painel e os personagens vinculados disponíveis. Escolha Depositar ou Retirar, selecione o item, a quantidade e o destino e revise a confirmação. Regras de negociação, quantidade e estado do personagem são validadas pelo servidor.", "bag,warehouse,depositar,retirar,item,inventário"),
    ("c0100000-0000-4000-8000-000000000019", "economy", "Posso trocar itens com outro jogador pelo painel?", "Use a opção de troca no Inventário quando o módulo estiver disponível.", "A troca parte de itens elegíveis da bag do painel e exige os dados do destinatário e da oferta. Confira item, quantidade e jogador antes de confirmar. Itens não negociáveis, quantidade insuficiente ou dados inválidos impedem a operação.", "trade,troca,enviar item,negociar"),
    ("c0100000-0000-4000-8000-000000000020", "commerce", "Como compro itens ou pacotes na Loja?", "Adicione ao carrinho, revise o pedido e conclua o checkout.", "A Loja pode reunir produtos avulsos e pacotes. O carrinho mostra itens, quantidades, descontos, bônus usado e total antes do checkout. Uma compra concluída preserva a composição daquele momento e entrega os itens na bag do painel para uso posterior.", "comprar,carrinho,checkout,pacote,produto"),
    ("c0100000-0000-4000-8000-000000000021", "commerce", "Como uso um cupom?", "Informe o código no carrinho e confira o desconto antes de comprar.", "Cupons podem ter validade, percentual, limite de uso e regras de elegibilidade. Quando vinculados a um apoiador, também seguem as regras do programa; o próprio apoiador não usa o próprio cupom. O resumo do carrinho informa se o código foi aceito e qual desconto será aplicado.", "cupom,código promocional,desconto,promoção"),
    ("c0100000-0000-4000-8000-000000000022", "commerce", "Como funciona o Marketplace?", "O Marketplace permite consultar e negociar anúncios disponíveis.", "Na área Marketplace você acompanha seus anúncios e as ações permitidas, como comprar ou cancelar. A venda de personagem usa custódia e regras próprias do servidor. Sempre confira personagem, preço, taxas e estado do anúncio antes da confirmação.", "mercado,vender personagem,comprar personagem,anúncio"),
    ("c0100000-0000-4000-8000-000000000023", "commerce", "Como funcionam os leilões?", "Abra Leilão para consultar ofertas, seus leilões e enviar lances.", "Cada leilão informa item, período, lance atual e condições. Um lance é validado contra saldo e regras vigentes, e a entrega ocorre conforme o encerramento processado pelo sistema. Não repita uma ação enquanto ela estiver sendo confirmada.", "auction,lance,item,arremate"),
    ("c0100000-0000-4000-8000-000000000024", "commerce", "Onde acompanho compras e movimentações?", "Consulte o histórico da área em que a operação foi feita.", "A Carteira lista transações de saldo; a Loja mantém o histórico de compras; Inventário, Marketplace, Leilão e Jogos mostram seus próprios registros quando aplicável. Se um estado continuar pendente, anote a operação e abra um chamado sem compartilhar senha ou códigos.", "histórico,recibo,compra pendente,transação"),
    ("c0100000-0000-4000-8000-000000000025", "games_rewards", "Quais jogos existem no painel?", "A área Jogos reúne as experiências habilitadas pela administração.", "Conforme a configuração, o PDL pode oferecer roleta, caixas, dados, caça-níquel, pesca e combates da economia de jogos. Cada atividade apresenta custo, prêmio, limite e regras antes de jogar. Resultados e consumos são registrados pelo sistema.", "roleta,caixa,dado,slots,pesca,minigame"),
    ("c0100000-0000-4000-8000-000000000026", "games_rewards", "Como funciona a pescaria?", "Escolha a vara e a isca na aba Pesca da área Jogos.", "A pescaria reúne vara, experiência, estoque de iscas, coleção e lançamentos recentes. A isca é consumida ao lançar, mesmo se o peixe escapar. Capturas bem-sucedidas entram na coleção e podem participar dos rankings configurados.", "peixe,isca,vara,coleção,fishing"),
    ("c0100000-0000-4000-8000-000000000027", "games_rewards", "Como resgato o bônus diário?", "Abra Jornada e recompensas e use o resgate disponível do dia.", "Durante uma temporada, o bônus usa o dia do calendário da temporada e permite um resgate por data local. Sem temporada ativa, o bônus simples configurado continua disponível. A tela informa o prêmio e se o resgate já foi realizado.", "login diário,daily bonus,calendário,recompensa diária"),
    ("c0100000-0000-4000-8000-000000000028", "games_rewards", "Como funcionam missões, passe e recompensas?", "Acompanhe objetivos e resgates em Jornada e recompensas.", "Missões contam eventos reais do período diário, semanal ou da temporada. Marcos e prêmios são resgatados uma única vez; recompensas de nível podem ter resgate automático e regras diferentes para a faixa premium. A própria tela mostra progresso, prazo e elegibilidade.", "battle pass,passe,missão,marco,premium,prêmio"),
    ("c0100000-0000-4000-8000-000000000029", "games_rewards", "Onde vejo meu progresso e os rankings?", "Use Progresso no painel e Rankings no site público.", "Progresso reúne os dados e recompensas ligados ao seu perfil. Rankings públicos exibem as categorias fornecidas pelo servidor; os jogos também podem ter classificações próprias baseadas em resultados positivos e partidas. A atualização depende da fonte de cada ranking.", "nível,xp,ranking,top,jornada"),
    ("c0100000-0000-4000-8000-000000000030", "community", "Onde encontro notícias, eventos, guias e roadmap?", "Use Notícias, Calendário, Wiki e Roadmap nas páginas públicas.", "Notícias concentra comunicados; Calendário apresenta eventos publicados; Wiki reúne guias; Roadmap mostra iniciativas e andamento quando o módulo está ativo. Esses conteúdos são mantidos pela equipe do servidor e podem ser consultados sem abrir o chat.", "notícia,evento,guia,wiki,roadmap,novidade"),
    ("c0100000-0000-4000-8000-000000000031", "community", "Como funciona o programa de apoiadores?", "Abra Apoiadores para consultar o programa e enviar uma candidatura.", "A candidatura passa por análise da equipe e não pode ser autoaprovada. Apoiadores aprovados podem ter cupom e comissão conforme as regras publicadas. Comissões consideram o saldo normal efetivamente pago após desconto e bônus, e o crédito de uma solicitação aprovada ocorre uma única vez.", "supporter,afiliado,comissão,candidatura,indicador"),
    ("c0100000-0000-4000-8000-000000000032", "community", "Como acompanho avisos do PDL?", "Abra Avisos no painel e consulte também as notícias públicas.", "Avisos reúne notificações relacionadas à sua conta e mostra as que ainda não foram lidas. Notícias publica comunicados gerais da comunidade. Quando o navegador e o servidor oferecerem Web Push, você também pode gerenciar essa permissão pelo fluxo apresentado.", "notificação,sino,push,comunicado,aviso"),
    ("c0100000-0000-4000-8000-000000000033", "support", "Como abro um chamado de atendimento?", "Abra Atendimento no painel e crie um chamado com os detalhes do problema.", "Informe um assunto claro, descreva o que aconteceu e inclua identificadores públicos ou horários quando forem úteis. Acompanhe as respostas na mesma área. Nunca envie senha, código de autenticação, link de recuperação ou segredo da conta.", "ticket,suporte,equipe,problema,bug"),
    ("c0100000-0000-4000-8000-000000000034", "support", "O Denkynho consegue acessar minha conta ou executar ações?", "Não. O Denkynho consulta apenas o FAQ público e orienta você.", "A conversa da Ajuda acontece no navegador e não consulta dados particulares, pagamentos, personagens ou saldo. O Denkynho não altera configurações nem executa operações. Para uma análise da sua conta, use Atendimento; o histórico deste chat não é enviado automaticamente.", "assistente,ia,privacidade,executar,acessar conta"),
    ("c0100000-0000-4000-8000-000000000035", "support", "Onde consulto os termos e a política de privacidade?", "Use os links Termos, Privacidade e Acordo nas páginas públicas.", "Os documentos legais publicados pelo PDL descrevem as condições de uso, o tratamento de dados e o acordo aplicável. Consulte sempre a versão exibida no portal. Para uma questão sobre sua conta ou seus dados, abra um chamado de atendimento.", "lgpd,dados pessoais,termos,política,acordo"),
    ("c0100000-0000-4000-8000-000000000036", "commerce", "Como adiciono saldo à carteira?", "Abra Carteira e escolha uma opção de saldo disponível.", "A Carteira apresenta os pacotes, moedas e métodos de pagamento habilitados no servidor. Revise valor, moeda, bônus e forma de pagamento antes de criar o pedido. O saldo é creditado somente após a confirmação válida do pagamento; acompanhe o estado do pedido na própria tela.", "colocar saldo,doação,pagamento,pix,cartão,moedas"),
    ("c0100000-0000-4000-8000-000000000037", "commerce", "O que faço quando um pagamento fica pendente ou falha?", "Consulte o estado do pedido na Carteira antes de tentar novamente.", "Um pagamento pode aguardar a confirmação do provedor. Atualize o estado do pedido e confira se ele foi aprovado, cancelado ou recusado. Não crie várias cobranças para o mesmo pagamento enquanto a primeira estiver pendente. Se o estado não mudar, abra um chamado e informe o identificador público do pedido, sem enviar dados bancários ou credenciais.", "pagamento pendente,recusado,falhou,cobrança,pedido"),
    ("c0100000-0000-4000-8000-000000000038", "game_accounts", "Como desvinculo uma conta L2 ou aumento meus slots?", "Use as ações disponíveis em Conta L2.", "A desvinculação exige uma conta pertencente ao usuário e segue as validações mostradas na tela. Quando a compra de slots estiver habilitada, Conta L2 também apresenta o custo e o novo limite antes da confirmação. Confira as consequências e o saldo antes de concluir.", "desvincular,unlink,slot,limite de contas,comprar slot"),
]


def seed_faq(apps, schema_editor):
    Faq = apps.get_model("content", "Faq")
    for order, (item_id, category, question, short_answer, answer, keywords) in enumerate(FAQ_ITEMS, 10):
        Faq.objects.update_or_create(
            id=UUID(item_id),
            defaults={
                "category": category,
                "question": question,
                "short_answer": short_answer,
                "answer": answer,
                "keywords": keywords,
                "order": order,
                "is_published": True,
            },
        )


def remove_seeded_faq(apps, schema_editor):
    Faq = apps.get_model("content", "Faq")
    Faq.objects.filter(id__in=[UUID(item[0]) for item in FAQ_ITEMS]).delete()


class Migration(migrations.Migration):
    dependencies = [("content", "0003_faq_response_layers")]

    operations = [migrations.RunPython(seed_faq, remove_seeded_faq)]
