# Generated by Django 6.0.8 on 2026-09-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_seed_pdl_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='audience',
            field=models.CharField(choices=[('public', 'Todos os usuários'), ('staff', 'Equipe'), ('superadmin', 'Superadministradores')], default='public', help_text='Público mínimo autorizado a receber este artigo no assistente.', max_length=16),
        ),
    ]
