# Generated by Django 6.0.8 on 2026-09-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_update_denkynho_privacy_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords_en',
            field=models.CharField(blank=True, help_text='English alternative terms separated by commas.', max_length=500),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='faq',
            name='short_answer_en',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
