# Generated by Django 6.0.8 on 2026-09-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_local_conversation_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='assistant_only',
            field=models.BooleanField(default=False, help_text='Se marcado, o artigo fica só na consulta do Denkynho e não aparece na página FAQ nem nas sugestões.'),
        ),
    ]
