from uuid import UUID

from django.db import migrations

# IDs fixos tornam a carga repetível. Estes artigos alimentam só a consulta do Denkynho.
PREFIX = "c0300000-0000-4000-8000-"
HANDBOOK = [
    (
        1, "public", "getting_started",
        "Passo a passo para criar conta e entrar no painel",
        "Crie a conta do portal, confirme o e-mail e faça login para abrir o painel.",
        "1) Abra Criar conta (/register) e preencha os dados pedidos. 2) Confirme o e-mail pelo link enviado; se não chegar, verifique spam e use reenviar quando a tela oferecer. 3) Entre em /login com o e-mail e a senha. 4) Depois do login você chega em /painel. 5) Em Conta L2, cadastre ou vincule a conta do jogo. A conta do portal e a conta L2 são registros diferentes.",
        "cadastro,criar conta,register,login,entrar,primeiros passos,painel",
        "Step by step to create an account and sign in",
        "Create the portal account, verify your email, then sign in to open the dashboard.",
        "1) Open Create account (/register) and fill in the requested details. 2) Confirm the email from the link; check spam and resend if the screen offers it. 3) Sign in at /login with email and password. 4) After login you reach /painel. 5) In L2 Account, register or link a game account. The portal account and the L2 account are different records.",
        "sign up,register,login,getting started,dashboard",
    ),
    (
        2, "public", "getting_started",
        "Como navegar no painel depois de entrar",
        "Use o menu do painel para abrir perfil, segurança, contas, economia, jogos e ajuda.",
        "No menu autenticado você encontra Painel (/painel), Meu perfil, Conta e segurança, Conta L2, Inventário, Carteira, Loja, Marketplace, Leilão, Jogos, Jornada e recompensas, Apoiadores, Progresso, Avisos, Atendimento e Ajuda. Módulos desativados pela administração somem do menu e bloqueiam a API, sem apagar dados. Telas públicas como Informações, Rankings, Wiki, Notícias, Roadmap, FAQ e Downloads continuam no site. Se um item não aparecer, confira avisos ou Atendimento.",
        "menu,navegar,painel,rotas,onde fica,como achar",
        "How to navigate the dashboard after signing in",
        "Use the dashboard menu for profile, security, accounts, economy, games, and help.",
        "The authenticated menu includes Dashboard (/painel), My profile, Account and security, L2 Account, Inventory, Wallet, Shop, Marketplace, Auctions, Games, Journey and rewards, Supporters, Progress, Notifications, Support, and Help. Disabled modules leave the menu and block their API without deleting data. Public pages such as Information, Rankings, Wiki, News, Roadmap, FAQ, and Downloads stay on the site. If an item is missing, check announcements or Support.",
        "menu,navigate,dashboard,where,find",
    ),
    (
        3, "public", "getting_started",
        "Quais páginas posso consultar sem fazer login",
        "O site público reúne informações, rankings, wiki, notícias, calendário, FAQ e downloads.",
        "Sem login você pode abrir Início (/), Informações (/informacoes), Rankings, Wiki, Notícias, Calendário (/calendar), FAQ (/faq), Downloads, Roadmap quando o módulo estiver ativo, e os documentos Termos, Privacidade e Acordo. Cadastro, recuperação de senha e verificação de e-mail também são públicos. Carteira, loja, inventário, contas L2 e atendimento exigem login. Use somente links publicados pelo próprio portal.",
        "público,sem login,site,informações,wiki,notícias,faq,downloads",
        "Which pages can I browse without signing in",
        "The public site covers information, rankings, wiki, news, calendar, FAQ, and downloads.",
        "Without signing in you can open Home (/), Information (/informacoes), Rankings, Wiki, News, Calendar (/calendar), FAQ (/faq), Downloads, Roadmap when enabled, and the Terms, Privacy, and Agreement documents. Registration, password recovery, and email verification are also public. Wallet, shop, inventory, L2 accounts, and support require login. Use only links published by the portal itself.",
        "public,without login,site,information,wiki,news,faq,downloads",
    ),
    (
        4, "public", "getting_started",
        "O que fazer quando um recurso some do menu",
        "Confira se o módulo está ativo; a administração pode pausá-lo sem apagar seus dados.",
        "1) Veja Avisos e as notícias públicas. 2) Recarregue a página depois de um aviso de manutenção. 3) Carteira, loja, inventário, marketplace, leilão, jogos, recompensas, apoiadores e roadmap podem ser desligados em Controle de recursos. 4) Com o módulo pausado, a rota e a API ficam bloqueadas, mas o histórico permanece. 5) Se você precisa daquele serviço agora, abra Atendimento e descreva a tela que tentou usar, sem enviar senha.",
        "sumiu,menu,desativado,indisponível,módulo,bloqueado,recurso",
        "What to do when a feature disappears from the menu",
        "Check whether the module is enabled; staff can pause it without deleting your data.",
        "1) Check Notifications and public news. 2) Reload after a maintenance notice. 3) Wallet, shop, inventory, marketplace, auctions, games, rewards, supporters, and roadmap can be turned off in resource control. 4) While paused, the route and API are blocked, but history remains. 5) If you need that service now, open Support and name the screen you tried, without sending a password.",
        "missing,menu,disabled,unavailable,module,blocked,feature",
    ),
    (
        5, "public", "account_security",
        "Passo a passo para recuperar a senha do portal",
        "Use Esqueci minha senha na tela de login e abra o link enviado ao e-mail da conta.",
        "1) Abra /login e escolha Esqueci minha senha (/forgot-password). 2) Informe o e-mail da conta do portal, não o login L2. 3) Abra o link recebido em /reset-password. 4) Defina uma senha nova e exclusiva. 5) Entre novamente. O link e os códigos são pessoais. Se a mensagem não chegar, confira spam e lixo eletrônico antes de abrir um chamado. Nunca envie a senha antiga ou o código no chat.",
        "esqueci senha,redefinir,reset,recuperar senha,forgot password,login",
        "Step by step to recover the portal password",
        "Use Forgot password on the sign-in page and open the link sent to the account email.",
        "1) Open /login and choose Forgot password (/forgot-password). 2) Enter the portal account email, not the L2 login. 3) Open the link at /reset-password. 4) Set a new unique password. 5) Sign in again. The link and codes are personal. If the message does not arrive, check spam before opening a ticket. Never send the old password or the code in chat.",
        "forgot password,reset,recover,login,email",
    ),
    (
        6, "public", "account_security",
        "Passo a passo para confirmar o endereço de e-mail",
        "Abra o link de verificação enviado pelo PDL ou solicite uma nova mensagem.",
        "1) Após o cadastro, abra o e-mail do PDL. 2) Use o link de /verify-email. 3) Se o endereço estiver errado, corrija-o nas opções disponíveis antes de pedir outro envio. 4) Confira spam e lixo eletrônico. 5) Sem confirmação, algumas ações do painel podem ficar limitadas. A confirmação associa aquele endereço à conta do portal; o atendimento não precisa do código para analisar um chamado.",
        "verificar email,confirmação,verify,e-mail não chegou,reenviar",
        "Step by step to verify your email address",
        "Open the verification link sent by PDL or request a new message.",
        "1) After registration, open the PDL email. 2) Use the /verify-email link. 3) If the address is wrong, correct it in the available options before requesting another send. 4) Check spam. 5) Without verification, some dashboard actions may stay limited. Verification ties that address to the portal account; support does not need the code to review a ticket.",
        "verify email,confirmation,resend,inbox",
    ),
    (
        7, "public", "account_security",
        "Como ativar a autenticação em duas etapas",
        "Abra Conta e segurança e ative o 2FA com o aplicativo autenticador quando a opção estiver disponível.",
        "1) Entre no painel e abra Conta e segurança (/painel/security). 2) Inicie o 2FA e siga o QR ou a chave mostrados no próprio aplicativo autenticador. 3) Guarde os códigos de recuperação em local seguro, fora do chat. 4) Confirme um código válido para concluir. 5) Nas próximas entradas, informe senha e código. O atendimento nunca pede o código temporário. Se perder o autenticador, use os códigos de recuperação ou abra um chamado sem enviar segredos.",
        "2fa,dois fatores,autenticador,otp,código,segurança",
        "How to enable two-factor authentication",
        "Open Account and security and enable 2FA with an authenticator app when the option is available.",
        "1) Sign in and open Account and security (/painel/security). 2) Start 2FA and follow the QR code or key in your authenticator app. 3) Store recovery codes somewhere safe, never in chat. 4) Confirm a valid code to finish. 5) Later sign-ins ask for password and code. Support never needs the temporary code. If you lose the authenticator, use recovery codes or open a ticket without sending secrets.",
        "2fa,two factor,authenticator,otp,security",
    ),
    (
        8, "public", "account_security",
        "Como cadastrar uma passkey",
        "Em Conta e segurança, adicione uma passkey do dispositivo quando o servidor oferecer esse método.",
        "1) Abra /painel/security. 2) Escolha cadastrar passkey. 3) Confirme no navegador ou no dispositivo (impressão digital, PIN ou chave de segurança). 4) Dê um nome fácil de reconhecer se a tela pedir. 5) Teste o próximo login. A passkey fica no dispositivo; não compartilhe prompts nem prints do cadastro. Se o método não aparecer, o servidor ainda não habilitou passkeys: use senha e 2FA.",
        "passkey,chave de acesso,webauthn,biometria,login sem senha",
        "How to register a passkey",
        "In Account and security, add a device passkey when the server offers that method.",
        "1) Open /painel/security. 2) Choose to register a passkey. 3) Confirm in the browser or device (fingerprint, PIN, or security key). 4) Give it a recognizable name if asked. 5) Try the next sign-in. The passkey stays on the device; do not share prompts or screenshots. If the option is missing, the server has not enabled passkeys: use password and 2FA.",
        "passkey,webauthn,passwordless,security key",
    ),
    (
        9, "public", "account_security",
        "Como entrar com uma conta social",
        "Na tela de login, escolha o provedor habilitado e conclua o retorno ao PDL.",
        "1) Abra /login. 2) Se um botão de provedor (por exemplo Google ou Discord) aparecer, escolha-o. 3) Autorize no site do provedor. 4) Aguarde o retorno em /auth/callback. 5) Se a opção não existir, use e-mail e senha. O acesso social só funciona quando a administração habilitou aquele provedor. Não envie tokens ou códigos do provedor no chat.",
        "oauth,google,discord,login social,provedor,entrar com",
        "How to sign in with a social account",
        "On the sign-in page, choose an enabled provider and finish the return to PDL.",
        "1) Open /login. 2) If a provider button (for example Google or Discord) is shown, choose it. 3) Authorize on the provider site. 4) Wait for the return at /auth/callback. 5) If the option is missing, use email and password. Social sign-in works only when staff enabled that provider. Do not send provider tokens or codes in chat.",
        "oauth,google,discord,social login,provider",
    ),
    (
        10, "public", "account_security",
        "Como alterar nome, avatar e dados do perfil",
        "Abra Meu perfil para editar os dados públicos permitidos da conta.",
        "1) No painel, abra Meu perfil (/painel/profile). 2) Atualize o nome de exibição e o avatar quando a tela oferecer envio. 3) Revise a bio e os demais campos públicos permitidos. 4) Salve e confira o resultado. Login, senha, 2FA e passkeys ficam em Conta e segurança, não no perfil. O nome de exibição não substitui o login L2 nem o apelido do personagem.",
        "perfil,avatar,foto,nome de exibição,bio,meu perfil",
        "How to change name, avatar, and profile details",
        "Open My profile to edit the allowed public account details.",
        "1) In the dashboard, open My profile (/painel/profile). 2) Update the display name and avatar when upload is offered. 3) Review the bio and other allowed public fields. 4) Save and check the result. Login, password, 2FA, and passkeys live in Account and security, not in the profile. The display name does not replace the L2 login or the character nickname.",
        "profile,avatar,photo,display name,bio",
    ),
    (
        11, "public", "account_security",
        "Como trocar a senha do portal estando logado",
        "Altere a senha do portal em Conta e segurança, sem usar a senha da conta L2.",
        "1) Abra /painel/security. 2) Use a ação de alterar senha. 3) Informe a senha atual e a nova senha exclusiva. 4) Confirme e entre de novo se a sessão pedir. Essa troca não altera a senha do jogo. Se você não lembra a senha atual, saia e use Esqueci minha senha. Não cole a senha nova no chat da Ajuda nem em um chamado.",
        "alterar senha,trocar senha,senha do portal,conta e segurança",
        "How to change the portal password while signed in",
        "Change the portal password in Account and security; it is not the L2 password.",
        "1) Open /painel/security. 2) Use the change-password action. 3) Enter the current password and a new unique password. 4) Confirm and sign in again if the session asks. This does not change the game password. If you do not remember the current password, sign out and use Forgot password. Do not paste the new password in Help chat or a ticket.",
        "change password,portal password,account security",
    ),
    (
        12, "public", "game_accounts",
        "Passo a passo para cadastrar uma conta L2",
        "No painel, abra Conta L2 e use Cadastrar conta com um login disponível.",
        "1) Entre no painel e abra Conta L2 (/painel/accounts). 2) Escolha Cadastrar conta. 3) Informe um login disponível e os demais dados pedidos na tela. 4) Confirme. 5) A conta passa a aparecer na lista vinculada a você. Os limites e requisitos exibidos são os válidos para este servidor. A senha do jogo não é a senha do portal. Depois, crie o personagem no cliente Lineage.",
        "criar conta l2,cadastrar conta,lineage,game account,login do jogo",
        "Step by step to register an L2 account",
        "In the dashboard, open L2 Account and use Register account with an available login.",
        "1) Sign in and open L2 Account (/painel/accounts). 2) Choose Register account. 3) Enter an available login and the other details shown. 4) Confirm. 5) The account appears in the list linked to you. Limits and requirements on screen are the ones for this server. The game password is not the portal password. After that, create the character in the Lineage client.",
        "create l2 account,register,lineage,game account",
    ),
    (
        13, "public", "game_accounts",
        "Passo a passo para vincular uma conta L2 que já existe",
        "Use Vincular conta em Conta L2 e conclua um dos métodos de comprovação habilitados.",
        "1) Abra /painel/accounts. 2) Escolha Vincular conta. 3) Informe o login da conta do jogo. 4) Conclua o método de comprovação oferecido, inclusive e-mail quando configurado. 5) Só vincule contas das quais você é o proprietário. A vinculação associa a conta L2 ao seu usuário do portal; não compartilhe senha do jogo para “agilizar” o processo.",
        "vincular,associar,link account,conta existente,conta l2",
        "Step by step to link an existing L2 account",
        "Use Link account in L2 Account and complete one of the enabled ownership checks.",
        "1) Open /painel/accounts. 2) Choose Link account. 3) Enter the game account login. 4) Complete the ownership check offered, including email when configured. 5) Only link accounts you own. Linking associates the L2 account with your portal user; do not share the game password to “speed up” the process.",
        "link account,existing account,associate,l2",
    ),
    (
        14, "public", "game_accounts",
        "Como alterar a senha da conta do jogo",
        "Abra a conta vinculada em Conta L2 e use a ação de senha daquela conta.",
        "1) Abra Conta L2. 2) Selecione a conta que pertence a você. 3) Use a ação de alterar senha do jogo. 4) Preencha os campos pedidos e confirme. 5) Guarde a nova senha fora do chat. Essa operação não muda a senha do portal. Se a conta não aparecer, ela ainda não está vinculada ao seu usuário.",
        "senha lineage,senha l2,senha do jogo,alterar senha conta",
        "How to change the game account password",
        "Open the linked account in L2 Account and use that account’s password action.",
        "1) Open L2 Account. 2) Select the account that belongs to you. 3) Use the game password action. 4) Fill in the requested fields and confirm. 5) Store the new password outside chat. This does not change the portal password. If the account is missing, it is not linked to your user yet.",
        "lineage password,l2 password,game password,change",
    ),
    (
        15, "public", "game_accounts",
        "Como consultar personagens e equipamentos",
        "Abra a conta em Conta L2 e entre na página do personagem para ver os dados disponíveis.",
        "1) Abra /painel/accounts. 2) Escolha a conta vinculada. 3) Clique no personagem para abrir /painel/accounts/<login>/<charId>. 4) Consulte os dados que a integração do servidor disponibiliza, inclusive equipamentos quando existirem. 5) Se uma alteração recente no jogo ainda não aparecer, atualize a consulta antes de abrir chamado. O Denkynho não lê o personagem por você.",
        "personagem,char,boneco,equipamento,inventário do char,conta l2",
        "How to view characters and equipment",
        "Open the account in L2 Account and open the character page for the available data.",
        "1) Open /painel/accounts. 2) Choose the linked account. 3) Open the character at /painel/accounts/<login>/<charId>. 4) Review the data the server integration provides, including equipment when available. 5) If a recent in-game change is missing, refresh before opening a ticket. Denkynho does not read the character for you.",
        "character,char,equipment,gear,l2 account",
    ),
    (
        16, "public", "game_accounts",
        "Como usar mudança de nick, sexo ou destravamento",
        "Abra o personagem, escolha o serviço disponível e revise requisitos e custo antes de confirmar.",
        "1) Abra o personagem em Conta L2. 2) Escolha o serviço: apelido, sexo ou destravamento, se estiver habilitado. 3) Leia requisitos, personagem elegível e custo mostrados na tela. 4) Confirme uma única vez. 5) Não repita o envio enquanto a operação estiver pendente. Só personagens de contas vinculadas ao seu usuário entram. Valores e disponibilidade são os da tela, não os de mensagens antigas.",
        "nick,nickname,sexo,gender,unstuck,destravar,serviço de personagem",
        "How to use nickname, gender, or unstuck services",
        "Open the character, choose an available service, and review requirements and cost before confirming.",
        "1) Open the character in L2 Account. 2) Choose nickname, gender, or unstuck if enabled. 3) Read the requirements, eligible character, and cost on screen. 4) Confirm once. 5) Do not resubmit while it is pending. Only characters from accounts linked to you are allowed. Prices and availability are those on screen, not from older messages.",
        "nickname,gender,unstuck,character service",
    ),
    (
        17, "public", "game_accounts",
        "Como desvincular uma conta L2 ou aumentar os slots",
        "Use as ações da própria Conta L2 e leia as consequências antes de confirmar.",
        "1) Abra /painel/accounts. 2) Para desvincular, escolha a conta sua e a ação de desvínculo; a conta do jogo não é apagada só por sair do painel. 3) Se a compra de slots estiver habilitada, a tela mostra o custo e o novo limite antes da confirmação. 4) Confira saldo e resumo. 5) Confirme só se aceitar o resultado. Depois de desvincular, a conta deixa de aparecer até uma nova vinculação.",
        "desvincular,unlink,slot,limite de contas,comprar slot",
        "How to unlink an L2 account or increase slots",
        "Use the actions on L2 Account and read the consequences before confirming.",
        "1) Open /painel/accounts. 2) To unlink, choose your account and the unlink action; the game account is not deleted just by leaving the dashboard. 3) If slot purchase is enabled, the screen shows the cost and the new limit before confirmation. 4) Check balance and summary. 5) Confirm only if you accept the result. After unlinking, the account disappears until it is linked again.",
        "unlink,slot,account limit,buy slot",
    ),
    (
        18, "public", "economy",
        "Como entender carteira, bônus e fichas",
        "São saldos diferentes: a carteira separa saldo normal e bônus; fichas servem aos jogos do painel.",
        "Abra Carteira (/painel/wallet). O saldo normal e o saldo de bônus aparecem separados; compras e promoções podem usar cada um de forma diferente. Fichas pertencem à economia dos jogos em /painel/games. Cada operação mostra qual saldo será gasto antes da confirmação. O histórico da carteira lista os lançamentos. O Denkynho não consulta o seu saldo atual.",
        "saldo,moedas,coin,bônus,tokens,fichas,carteira",
        "How to understand wallet, bonus, and tokens",
        "They are different balances: the wallet splits normal and bonus funds; tokens belong to dashboard games.",
        "Open Wallet (/painel/wallet). Normal balance and bonus appear separately; purchases and promotions may treat each one differently. Tokens belong to the games economy at /painel/games. Each operation shows which balance it will spend before confirmation. Wallet history lists the entries. Denkynho does not look up your current balance.",
        "balance,coins,bonus,tokens,wallet",
    ),
    (
        19, "public", "economy",
        "Passo a passo para adicionar saldo à carteira",
        "Abra Carteira, escolha um pacote ou método habilitado e só confirme depois de revisar valor e pagamento.",
        "1) Abra /painel/wallet. 2) Escolha um pacote, moeda ou método de pagamento habilitado neste servidor. 3) Revise valor, moeda, bônus previsto e forma de pagamento. 4) Crie o pedido. 5) Conclua o pagamento no provedor. O saldo entra só após confirmação válida. Acompanhe o estado na própria Carteira. Não abra várias cobranças iguais enquanto a primeira estiver pendente.",
        "colocar saldo,doação,pagamento,pix,cartão,comprar moedas,depósito",
        "Step by step to add funds to the wallet",
        "Open Wallet, choose an enabled package or method, and confirm only after reviewing amount and payment.",
        "1) Open /painel/wallet. 2) Choose a package, currency, or payment method enabled on this server. 3) Review amount, currency, expected bonus, and payment method. 4) Create the order. 5) Finish payment at the provider. Balance is credited only after a valid confirmation. Track status in Wallet. Do not open several identical charges while the first is pending.",
        "add funds,donation,payment,pix,card,buy coins",
    ),
    (
        20, "public", "economy",
        "O que fazer se o pagamento ficar pendente ou falhar",
        "Atualize o pedido na Carteira e não crie outra cobrança enquanto a primeira não tiver estado final.",
        "1) Abra Carteira e localize o pedido. 2) Atualize o estado: aprovado, pendente, cancelado ou recusado. 3) Se ainda estiver pendente, aguarde a confirmação do provedor. 4) Só tente de novo depois de cancelado ou recusado. 5) Se não mudar, abra Atendimento com o identificador público do pedido, sem dados bancários nem senha. Um pagamento pode demorar a refletir no saldo mesmo depois da aprovação.",
        "pagamento pendente,falhou,recusado,cobrança duplicada,pedido",
        "What to do if a payment stays pending or fails",
        "Refresh the order in Wallet and do not create another charge until the first has a final status.",
        "1) Open Wallet and find the order. 2) Refresh the status: approved, pending, cancelled, or declined. 3) If it is still pending, wait for the provider confirmation. 4) Retry only after cancelled or declined. 5) If it does not change, open Support with the public order identifier, without bank details or passwords. Balance may take time to update even after approval.",
        "pending payment,failed,declined,duplicate charge,order",
    ),
    (
        21, "public", "economy",
        "Como transferir saldo para outro jogador",
        "Use Transferir na Carteira, confira destinatário e valor e confirme uma única vez.",
        "1) Abra /painel/wallet. 2) Escolha Transferir. 3) Informe o destinatário e o valor. 4) Veja qual saldo será usado e o resumo. 5) Confirme só se os dados estiverem corretos. A operação pode ser recusada por destinatário inválido, saldo insuficiente ou limites do servidor. Não repita o envio enquanto estiver pendente. O Denkynho não executa a transferência.",
        "transferir,enviar moedas,p2p,destinatário,pix de saldo",
        "How to transfer balance to another player",
        "Use Transfer in Wallet, check recipient and amount, and confirm once.",
        "1) Open /painel/wallet. 2) Choose Transfer. 3) Enter the recipient and amount. 4) See which balance will be used and the summary. 5) Confirm only if the details are correct. It can be refused for an invalid recipient, insufficient balance, or server limits. Do not resubmit while pending. Denkynho does not perform the transfer.",
        "transfer,send coins,p2p,recipient",
    ),
    (
        22, "public", "economy",
        "Passo a passo do câmbio entre painel e jogo",
        "Abra Carteira, entre em câmbio com o jogo e revise direção, taxa e resultado antes de confirmar.",
        "1) Abra /painel/wallet/jogo. 2) Escolha a direção (painel para o jogo ou o inverso). 3) Informe o valor. 4) Confira taxa, limites e o resultado previsto na tela. 5) Confirme uma vez. Se a operação ficar pendente após falha de comunicação, consulte o histórico e não repita com dados diferentes; o recibo evita duplicidade. Atendimento pode conferir o identificador, sem senha.",
        "exchange,câmbio,adena,converter,jogo,pendente,wallet jogo",
        "Step by step for exchange between dashboard and game",
        "Open Wallet, enter game exchange, and review direction, rate, and result before confirming.",
        "1) Open /painel/wallet/jogo. 2) Choose the direction (dashboard to game or the reverse). 3) Enter the amount. 4) Check the rate, limits, and preview on screen. 5) Confirm once. If it stays pending after a communication failure, check history and do not retry with different data; the receipt prevents duplicates. Support can check the identifier, without a password.",
        "exchange,adena,convert,game,pending",
    ),
    (
        23, "public", "economy",
        "Como depositar e retirar itens do inventário",
        "Use Inventário para mover itens elegíveis entre a bag do painel e um personagem vinculado.",
        "1) Abra Inventário (/painel/inventory). 2) Veja a bag do painel e os personagens disponíveis. 3) Escolha Depositar ou Retirar. 4) Selecione item, quantidade e destino. 5) Revise a confirmação e envie uma vez. Regras de negociação, quantidade e estado do personagem são validadas pelo servidor. Personagens de contas não vinculadas não aparecem. Não repita enquanto a movimentação estiver em andamento.",
        "bag,warehouse,depositar,retirar,item,inventário,wh",
        "How to deposit and withdraw inventory items",
        "Use Inventory to move eligible items between the dashboard bag and a linked character.",
        "1) Open Inventory (/painel/inventory). 2) Review the dashboard bag and available characters. 3) Choose Deposit or Withdraw. 4) Select the item, quantity, and destination. 5) Review confirmation and submit once. Trade rules, quantity, and character state are validated by the server. Characters from unlinked accounts do not appear. Do not retry while the move is running.",
        "bag,warehouse,deposit,withdraw,item,inventory",
    ),
    (
        24, "public", "economy",
        "Como trocar itens com outro jogador pelo painel",
        "No Inventário, use a troca quando o módulo estiver disponível e confira item, quantidade e destinatário.",
        "1) Abra /painel/inventory. 2) Escolha a opção de troca. 3) Selecione itens elegíveis da bag do painel. 4) Informe o destinatário e a oferta. 5) Confira tudo e confirme. Itens não negociáveis, quantidade insuficiente ou dados inválidos impedem a operação. A troca do painel não substitui o trade dentro do jogo. Se a opção não aparecer, o módulo pode estar desativado.",
        "trade,troca,enviar item,negociar,player trade",
        "How to trade items with another player through the dashboard",
        "In Inventory, use trade when the module is available and check item, quantity, and recipient.",
        "1) Open /painel/inventory. 2) Choose trade. 3) Select eligible items from the dashboard bag. 4) Enter the recipient and offer. 5) Review everything and confirm. Non-tradable items, insufficient quantity, or invalid data block the operation. Dashboard trade does not replace in-game trade. If the option is missing, the module may be disabled.",
        "trade,send item,player trade",
    ),
    (
        25, "public", "commerce",
        "Passo a passo para comprar na Loja",
        "Adicione produtos ou pacotes ao carrinho, revise o resumo e conclua o checkout uma vez.",
        "1) Abra Loja (/painel/shop). 2) Escolha itens avulsos ou pacotes. 3) Ajuste quantidades no carrinho. 4) Confira descontos, bônus usado e total. 5) Conclua o checkout. A compra preserva a composição daquele momento e entrega na bag do painel. Alterar um pacote depois não muda pedidos já pagos. Não clique de novo enquanto o envio estiver ocupado.",
        "comprar,carrinho,checkout,pacote,produto,loja",
        "Step by step to buy from the Shop",
        "Add products or bundles to the cart, review the summary, and complete checkout once.",
        "1) Open Shop (/painel/shop). 2) Choose individual items or bundles. 3) Adjust quantities in the cart. 4) Check discounts, bonus used, and total. 5) Complete checkout. The purchase keeps that composition and delivers to the dashboard bag. Changing a bundle later does not change paid orders. Do not click again while submit is busy.",
        "buy,cart,checkout,bundle,product,shop",
    ),
    (
        26, "public", "commerce",
        "Como aplicar um cupom no carrinho",
        "Informe o código no carrinho e só finalize depois de ver o desconto aceito no resumo.",
        "1) Monte o carrinho em /painel/shop. 2) Digite o código do cupom. 3) Confira se o desconto apareceu. 4) Veja validade, percentual e regras de elegibilidade na própria tela. 5) Conclua a compra. Cupons podem ter limite de uso e vínculo com apoiador; o próprio apoiador não usa o próprio cupom. Se o código for recusado, o resumo explica o motivo sem precisar de senha.",
        "cupom,código promocional,desconto,promoção,coupon",
        "How to apply a coupon in the cart",
        "Enter the code in the cart and finish only after the accepted discount appears in the summary.",
        "1) Build the cart at /painel/shop. 2) Enter the coupon code. 3) Check that the discount appeared. 4) Read validity, percent, and eligibility on the screen. 5) Complete the purchase. Coupons may have usage limits and a supporter link; a supporter cannot use their own coupon. If the code is refused, the summary explains why without needing a password.",
        "coupon,promo code,discount,promotion",
    ),
    (
        27, "public", "commerce",
        "Como anunciar ou comprar no Marketplace",
        "Abra Marketplace, confira personagem, preço e taxas e use comprar ou cancelar conforme as regras.",
        "1) Abra /painel/marketplace. 2) Para vender, siga o fluxo de anúncio do personagem com a custódia do servidor. 3) Para comprar, abra o anúncio e leia personagem, preço, taxas e estado. 4) Confirme uma vez. 5) Acompanhe seus anúncios na mesma área. Cancele somente pelas ações permitidas. Sempre confira o personagem certo. Valores são os da tela.",
        "mercado,vender personagem,comprar personagem,anúncio,marketplace",
        "How to list or buy on the Marketplace",
        "Open Marketplace, check character, price, and fees, then buy or cancel under the displayed rules.",
        "1) Open /painel/marketplace. 2) To sell, follow the character listing flow with server custody. 3) To buy, open the listing and read character, price, fees, and status. 4) Confirm once. 5) Track your listings in the same area. Cancel only with the allowed actions. Always check the correct character. Amounts are those on screen.",
        "market,sell character,buy character,listing,marketplace",
    ),
    (
        28, "public", "commerce",
        "Passo a passo para participar de um leilão",
        "Abra Leilão, leia item, prazo e lance atual e envie um lance válido uma única vez.",
        "1) Abra Leilão (/painel/auctions). 2) Consulte ofertas e os seus leilões. 3) Leia item, período, lance atual e condições. 4) Envie o lance; o sistema valida saldo e regras. 5) Aguarde o encerramento processado pelo sistema para a entrega. Não repita o lance enquanto a confirmação estiver em andamento. Se o módulo não aparecer, ele pode estar desativado.",
        "auction,leilão,lance,bid,arremate,item",
        "Step by step to take part in an auction",
        "Open Auctions, read the item, period, and current bid, then send one valid bid.",
        "1) Open Auctions (/painel/auctions). 2) Review offers and your auctions. 3) Read item, period, current bid, and conditions. 4) Send the bid; the system validates balance and rules. 5) Wait for the processed closing before delivery. Do not repeat the bid while confirmation is running. If the module is missing, it may be disabled.",
        "auction,bid,item,lot",
    ),
    (
        29, "public", "commerce",
        "Onde acompanhar compras, pedidos e movimentações",
        "Abra o histórico da área em que a operação foi feita: Carteira, Loja, Inventário, Marketplace, Leilão ou Jogos.",
        "Carteira lista transações de saldo e pedidos de pagamento. Loja guarda o histórico de compras. Inventário, Marketplace, Leilão e Jogos mostram os próprios registros. Se um estado continuar pendente, anote o identificador público visível na tela e abra Atendimento. Não envie senha, comprovante bancário completo nem códigos. O Denkynho não consulta o seu histórico particular.",
        "histórico,recibo,compra pendente,transação,pedido,extrato",
        "Where to track purchases, orders, and movements",
        "Open the history in the area where the operation was made: Wallet, Shop, Inventory, Marketplace, Auctions, or Games.",
        "Wallet lists balance transactions and payment orders. Shop keeps purchase history. Inventory, Marketplace, Auctions, and Games show their own records. If a status stays pending, note the public identifier on screen and open Support. Do not send passwords, full bank receipts, or codes. Denkynho does not look up your private history.",
        "history,receipt,pending purchase,transaction,order",
    ),
    (
        30, "public", "games_rewards",
        "Como jogar roleta, caixas, dados e slots",
        "Abra Jogos, escolha a atividade habilitada e leia custo, prêmio e limite antes de jogar.",
        "1) Abra Jogos (/painel/games). 2) Escolha roleta, caixas, dados, caça-níquel ou outro módulo ligado pela administração. 3) Leia custo, prêmio possível e limites na própria tela. 4) Confirme a jogada uma vez. 5) Resultados e consumos ficam no registro da área. Cada jogo pode ter configuração própria além do módulo geral. O Denkynho não inicia partidas nem informa o resultado da sua última jogada.",
        "roleta,caixa,dado,slots,caça-níquel,minigame,jogos",
        "How to play roulette, boxes, dice, and slots",
        "Open Games, choose an enabled activity, and read cost, prize, and limit before playing.",
        "1) Open Games (/painel/games). 2) Choose roulette, boxes, dice, slots, or another module enabled by staff. 3) Read cost, possible prize, and limits on the screen. 4) Confirm the play once. 5) Results and spends stay in that area’s records. Each game can have its own settings besides the general module. Denkynho does not start matches or report your last result.",
        "roulette,box,dice,slots,minigame,games",
    ),
    (
        31, "public", "games_rewards",
        "Passo a passo da pescaria no painel",
        "Na aba Pesca, escolha vara e isca; a isca é consumida no lançamento, mesmo se o peixe escapar.",
        "1) Abra /painel/games e a aba Pesca. 2) Confira vara, experiência, estoque de iscas e coleção. 3) Selecione a isca. 4) Lance. 5) Capturas bem-sucedidas entram na coleção e podem ir aos rankings configurados. Iscas custam fichas e saem do estoque ao lançar. O endereço antigo de pesca em recompensas redireciona para esta aba. Se Pesca não aparecer, o módulo de jogos pode estar pausado.",
        "peixe,isca,vara,coleção,fishing,pesca,pescaria",
        "Step by step for dashboard fishing",
        "In the Fishing tab, choose rod and bait; bait is consumed when you cast, even if the fish escapes.",
        "1) Open /painel/games and the Fishing tab. 2) Check rod, experience, bait stock, and collection. 3) Select bait. 4) Cast. 5) Successful catches enter the collection and may appear on configured rankings. Bait costs tokens and leaves stock when you cast. The old rewards fishing address redirects here. If Fishing is missing, the games module may be paused.",
        "fish,bait,rod,collection,fishing",
    ),
    (
        32, "public", "games_rewards",
        "Como resgatar o bônus diário",
        "Abra Jornada e recompensas e use o resgate disponível do dia no calendário da temporada.",
        "1) Abra /painel/recompensas. 2) Localize o bônus do dia. 3) Leia o prêmio mostrado. 4) Resgate uma vez. Com temporada ativa, vale o dia do calendário da temporada, não uma sequência pessoal de logins. Sem temporada, o bônus simples configurado continua. O limite é um resgate por data local. A tela informa se você já resgatou.",
        "login diário,daily bonus,calendário,recompensa diária,bônus",
        "How to claim the daily bonus",
        "Open Journey and rewards and claim the reward available for the current day on the season calendar.",
        "1) Open /painel/recompensas. 2) Find today’s bonus. 3) Read the prize shown. 4) Claim once. With an active season, the season calendar day counts, not a personal login streak. Without a season, the configured simple bonus remains. The limit is one claim per local date. The screen shows whether you already claimed.",
        "daily login,daily bonus,calendar,reward",
    ),
    (
        33, "public", "games_rewards",
        "Como acompanhar missões, passe e marcos",
        "Em Jornada e recompensas, veja progresso, prazo e resgates; marcos e prêmios saem só uma vez.",
        "1) Abra /painel/recompensas. 2) Acompanhe missões diárias, semanais ou da temporada — elas contam eventos reais do período. 3) Resgate marcos e prêmios disponíveis. 4) Confira a faixa premium se existir. 5) Trocas consomem o item e o encantamento exatos da bag. Resgate automático, quando ligado, cobre prêmios de nível e respeita premium. A tela mostra elegibilidade e prazo.",
        "battle pass,passe,missão,marco,premium,prêmio,jornada",
        "How to follow quests, the pass, and milestones",
        "In Journey and rewards, check progress, deadlines, and claims; milestones and prizes are claimed only once.",
        "1) Open /painel/recompensas. 2) Follow daily, weekly, or season quests — they count real events in the period. 3) Claim available milestones and prizes. 4) Check the premium track if it exists. 5) Exchanges consume the exact item and enchantment from the bag. Auto-claim, when enabled, covers level prizes and respects premium. The screen shows eligibility and deadlines.",
        "battle pass,quest,milestone,premium,reward,journey",
    ),
    (
        34, "public", "games_rewards",
        "Como ver progresso, níveis e rankings",
        "Use Progresso no painel para o seu perfil e Rankings no site público para classificações do servidor.",
        "Progresso (/painel/progress) reúne dados e recompensas ligados ao seu perfil. Rankings públicos (/rankings) mostram categorias fornecidas pelo servidor. Os jogos podem ter classificações próprias com base em resultados positivos e partidas. A atualização depende da fonte de cada ranking. O Denkynho não informa a sua posição atual.",
        "nível,xp,ranking,top,jornada,progresso,classificação",
        "How to see progress, levels, and rankings",
        "Use Progress in the dashboard for your profile and Rankings on the public site for server boards.",
        "Progress (/painel/progress) gathers data and rewards tied to your profile. Public rankings (/rankings) show categories supplied by the server. Games may have their own boards based on positive results and matches. Updates depend on each ranking’s source. Denkynho does not tell your current position.",
        "level,xp,ranking,top,journey,progress",
    ),
    (
        35, "public", "community",
        "Como consultar notícias, wiki, calendário e roadmap",
        "Use as páginas públicas Notícias, Wiki, Calendário e Roadmap; o conteúdo é mantido pela equipe.",
        "Notícias (/news) concentra comunicados. Wiki (/wiki) reúne guias publicados. Calendário (/calendar) mostra eventos. Roadmap (/roadmap) apresenta iniciativas quando o módulo está ativo; o detalhe fica em /roadmap/<id>. Esses conteúdos podem ser lidos sem abrir o chat. Se o Roadmap não aparecer, ele pode estar desativado. Não use links de terceiros no lugar das páginas oficiais.",
        "notícia,evento,guia,wiki,roadmap,novidade,calendário",
        "How to read news, wiki, calendar, and roadmap",
        "Use the public News, Wiki, Calendar, and Roadmap pages; staff maintain that content.",
        "News (/news) holds announcements. Wiki (/wiki) gathers published guides. Calendar (/calendar) shows events. Roadmap (/roadmap) presents initiatives when the module is on; details are at /roadmap/<id>. You can read these without opening chat. If Roadmap is missing, it may be disabled. Do not replace official pages with third-party links.",
        "news,event,guide,wiki,roadmap,calendar",
    ),
    (
        36, "public", "community",
        "Passo a passo para se candidatar a apoiador",
        "Abra Apoiadores, leia as regras e envie a candidatura para análise da equipe; não há autoaprovação.",
        "1) Abra /painel/apoiadores. 2) Leia o programa, cupom e comissão descritos na tela. 3) Envie a candidatura. 4) Aguarde a análise; você não pode se autoaprovar. 5) Se for aprovado, o papel de jogador passa a apoiador sem remover privilégios de equipe. Comissões usam o saldo normal efetivamente pago, após desconto e bônus, e o crédito de uma solicitação aprovada ocorre uma vez. O apoiador não usa o próprio cupom.",
        "supporter,afiliado,comissão,candidatura,indicador,apoiador",
        "Step by step to apply as a supporter",
        "Open Supporters, read the rules, and submit an application for staff review; there is no self-approval.",
        "1) Open /painel/apoiadores. 2) Read the program, coupon, and commission on screen. 3) Submit the application. 4) Wait for review; you cannot approve yourself. 5) If approved, the player role becomes supporter without removing staff privileges. Commissions use the normal balance actually paid after discount and bonus, and an approved request credits once. A supporter cannot use their own coupon.",
        "supporter,affiliate,commission,application",
    ),
    (
        37, "public", "community",
        "Como acompanhar avisos e permissões de push",
        "Abra Avisos no painel para notificações da conta e gerencie Web Push pelo fluxo apresentado no navegador.",
        "1) Abra Avisos (/painel/notifications) para ver o que ainda não foi lido. 2) Consulte também Notícias para comunicados gerais. 3) Se o navegador e o servidor oferecerem Web Push, siga o pedido de permissão na própria tela. 4) Você pode recusar ou revogar depois nas configurações do navegador. O Denkynho não envia push e não marca avisos como lidos.",
        "notificação,sino,push,comunicado,aviso,web push",
        "How to follow notifications and push permissions",
        "Open Notifications in the dashboard for account alerts and manage Web Push through the browser prompt.",
        "1) Open Notifications (/painel/notifications) to see unread items. 2) Also check News for general announcements. 3) If the browser and server offer Web Push, follow the permission prompt on that screen. 4) You can refuse or revoke later in browser settings. Denkynho does not send push and does not mark alerts as read.",
        "notification,bell,push,announcement,web push",
    ),
    (
        38, "public", "community",
        "Onde baixar o cliente e os arquivos oficiais",
        "Use somente a página Downloads do portal para cliente, patch e arquivos publicados.",
        "Abra Downloads (/downloads). Baixe só o que a equipe publicou ali. Evite links de terceiros, atalhos recebidos em mensagem e arquivos com nome parecido. Patch e cliente oficiais mudam conforme o servidor; a lista da página é a fonte. Se um arquivo falhar, tente de novo pela mesma página ou abra Atendimento descrevendo o título do link, sem enviar executáveis.",
        "download,cliente,patch,launcher,arquivo,baixar",
        "Where to download the client and official files",
        "Use only the portal Downloads page for client, patch, and published files.",
        "Open Downloads (/downloads). Download only what staff published there. Avoid third-party links, shortcuts from messages, and look-alike files. Official client and patch change with the server; the page list is the source. If a file fails, retry from the same page or open Support naming the link title, without sending executables.",
        "download,client,patch,launcher,file",
    ),
    (
        39, "public", "community",
        "Onde ver status e informações do servidor",
        "Abra Informações para status publicado, chronicle e dados oficiais do servidor.",
        "A página Informações (/informacoes) mostra o que a administração publicou sobre Login Server, Game Server e dados do servidor. Rankings e wiki não substituem esse status. Se aparecer offline, aguarde um comunicado em Notícias ou Avisos antes de abrir chamado só por instabilidade breve. Use os números e horários da própria tela; o chat não consulta o status ao vivo.",
        "online,offline,status,servidor,informações,chronicle,rates",
        "Where to see server status and information",
        "Open Information for published status, chronicle, and official server data.",
        "The Information page (/informacoes) shows what staff published about Login Server, Game Server, and server data. Rankings and wiki do not replace that status. If it looks offline, wait for News or Notifications before opening a ticket only for a brief outage. Use the numbers and times on that screen; chat does not query live status.",
        "online,offline,status,server,information,chronicle,rates",
    ),
    (
        40, "public", "support",
        "Passo a passo para abrir um chamado de atendimento",
        "Abra Atendimento, descreva o problema com horários e identificadores públicos, sem senhas ou códigos.",
        "1) Entre no painel e abra Atendimento (/painel/support). 2) Crie um chamado com assunto claro. 3) Diga o que aconteceu, em qual tela e quando. 4) Inclua identificadores públicos (pedido, personagem visível, horário). 5) Acompanhe as respostas na mesma área. Nunca envie senha, 2FA, passkey, link de recuperação ou senha L2. O botão Atendimento da equipe na Ajuda abre essa tela sem enviar o histórico do chat.",
        "ticket,suporte,chamado,equipe,problema,bug,atendimento",
        "Step by step to open a support ticket",
        "Open Support, describe the problem with times and public identifiers, without passwords or codes.",
        "1) Sign in and open Support (/painel/support). 2) Create a ticket with a clear subject. 3) Say what happened, which screen, and when. 4) Include public identifiers (order, visible character, time). 5) Follow replies in the same area. Never send passwords, 2FA, passkeys, recovery links, or L2 passwords. Contact the team on Help opens that screen without sending chat history.",
        "ticket,support,staff,problem,bug",
    ),
    (
        41, "public", "support",
        "Como conversar com o Denkynho na Ajuda",
        "Abra Ajuda, escreva a dúvida e envie com Enter; Shift+Enter quebra a linha.",
        "1) Abra /painel/ajuda. 2) Escreva até 1.000 caracteres. 3) Enter envia; Shift+Enter quebra a linha. 4) Você pode filtrar sugestões por assunto ou tocar numa pergunta. 5) Nova conversa limpa o histórico desta tela. Clique no Denkynho para dicas, idioma, animações e FAQ público. Conversar só foca o campo, sem enviar. Não envie senhas. O contexto vale enquanto a conversa estiver aberta e some ao recarregar.",
        "ajuda,denkynho,chat,como perguntar,assistente,conversar",
        "How to chat with Denkynho in Help",
        "Open Help, type the question, and send with Enter; Shift+Enter adds a line.",
        "1) Open /painel/ajuda. 2) Write up to 1,000 characters. 3) Enter sends; Shift+Enter adds a line. 4) You can filter suggestions by topic or tap a question. 5) New conversation clears this screen’s history. Click Denkynho for tips, language, animations, and the public FAQ. Chat only focuses the field, without sending. Never send passwords. Context lasts while this conversation stays open and disappears on reload.",
        "help,denkynho,chat,ask,assistant",
    ),
    (
        42, "public", "support",
        "O que o Denkynho pode e não pode fazer",
        "Ele orienta com o FAQ autorizado da sua sessão e não executa ações nem lê saldo, personagem ou pagamento.",
        "A Ajuda usa sua identidade autenticada para escolher orientações do seu papel. Jogadores recebem artigos públicos; equipe recebe também os da staff; superadministradores recebem todos. O Denkynho não altera senha, não transfere saldo, não abre chamado sozinho e não acessa dados particulares. Mensagens podem ir a um modelo local no servidor, sem IA na nuvem. Transcrições não ficam no banco. Para um caso da sua conta, use Atendimento.",
        "assistente,ia,privacidade,executar,acessar conta,limites do denkynho",
        "What Denkynho can and cannot do",
        "He guides from FAQ authorized for your session and does not perform actions or read balance, character, or payment data.",
        "Help uses your authenticated identity to choose guidance for your role. Players get public articles; staff also get staff articles; superadministrators get all. Denkynho does not change passwords, transfer balance, open tickets by himself, or access private data. Messages may go to a local model on the server, not cloud AI. Transcripts are not stored in the database. For an account-specific case, use Support.",
        "assistant,privacy,actions,account access,limits",
    ),
    (
        43, "public", "support",
        "Onde ler termos, privacidade e acordo",
        "Use os links Termos, Privacidade e Acordo nas páginas públicas e consulte sempre a versão exibida no portal.",
        "Abra /terms, /privacy e /agreement. Esses documentos descrevem condições de uso, tratamento de dados e o acordo aplicável. A versão válida é a publicada no portal, não um arquivo antigo recebido por mensagem. Dúvidas sobre a sua conta ou os seus dados vão para Atendimento, não para o chat. O Denkynho resume o que está nessas páginas oficiais, sem inventar cláusulas.",
        "lgpd,dados pessoais,termos,política,acordo,privacidade",
        "Where to read terms, privacy, and the agreement",
        "Use the public Terms, Privacy, and Agreement links and always read the version shown on the portal.",
        "Open /terms, /privacy, and /agreement. Those documents describe terms of use, data handling, and the applicable agreement. The valid version is the one published on the portal, not an old file from a message. Questions about your account or your data go to Support, not chat. Denkynho summarizes those official pages and does not invent clauses.",
        "privacy,personal data,terms,policy,agreement",
    ),
    (
        44, "public", "support",
        "Como usar idioma, dicas e nova conversa na Ajuda",
        "No menu do Denkynho você troca o idioma, pede uma dica local e reinicia a conversa sem enviar o histórico.",
        "Clique ou toque no personagem. Idioma (português ou inglês) limpa o contexto desta tela. Me dê uma dica mostra orientações locais de uso e segurança, sem chamar a IA. Conversar fecha o menu e foca o campo. Nova conversa no chat zera histórico e rascunho. No celular, arraste o personagem ou use as setas; Reposicionar volta ao lugar inicial. Animar personagem desliga movimentos; o dispositivo pode forçar movimento reduzido.",
        "idioma,dica,nova conversa,menu denkynho,arrastar,animar",
        "How to use language, tips, and a new conversation in Help",
        "In Denkynho’s menu you switch language, get a local tip, and restart the conversation without sending history.",
        "Click or tap the character. Language (Portuguese or English) clears this screen’s context. Give me a tip shows local usage and safety notes without calling AI. Chat closes the menu and focuses the field. New conversation clears history and draft. On a phone, drag the character or use arrow keys; Reset position returns to the start. Animate character turns motion off; the device may force reduced motion.",
        "language,tip,new conversation,menu,drag,animate",
    ),
    (
        45, "public", "economy",
        "Como conferir o histórico da carteira",
        "Abra Carteira e use o histórico da própria tela para lançamentos de saldo, bônus e pedidos.",
        "1) Abra /painel/wallet. 2) Localize a lista de movimentações. 3) Confira data, tipo e valor de cada lançamento. 4) Pedidos de pagamento também aparecem ali com o estado. 5) Para câmbio com o jogo, use /painel/wallet/jogo e o histórico daquela operação. Se um lançamento esperado não existir, não crie outra cobrança: abra Atendimento com o identificador visível. O chat não lista o seu extrato.",
        "histórico carteira,extrato,lançamento,movimentação,saldo",
        "How to check wallet history",
        "Open Wallet and use that screen’s history for balance entries, bonus, and orders.",
        "1) Open /painel/wallet. 2) Find the movement list. 3) Check date, type, and amount of each entry. 4) Payment orders also appear there with status. 5) For game exchange, use /painel/wallet/jogo and that operation’s history. If an expected entry is missing, do not create another charge: open Support with the visible identifier. Chat does not list your statement.",
        "wallet history,statement,entry,movement,balance",
    ),
    (
        46, "staff", "support",
        "Como a equipe atende a fila de chamados",
        "Abra a Fila de chamados na central da equipe, registre a orientação no chamado certo e nunca peça senhas.",
        "1) Entre no painel da equipe em /painel/admin. 2) Abra Fila de chamados (/painel/admin/atendimento). 3) Filtre pela fila autorizada ao seu papel. 4) Responda no chamado correto, com horário e identificadores públicos. 5) Preserve dados do jogador; não copie senhas, códigos 2FA, passkeys ou links de recuperação para notas. A presença desta orientação no Denkynho não amplia permissões: a API continua validando o acesso.",
        "staff,equipe,chamado,ticket,fila,atendimento interno,sla",
        "How staff handle the support queue",
        "Open the ticket queue in the staff hub, write guidance on the correct ticket, and never ask for passwords.",
        "1) Open the staff hub at /painel/admin. 2) Open the ticket queue (/painel/admin/atendimento). 3) Filter to the queue allowed for your role. 4) Reply on the correct ticket with times and public identifiers. 5) Protect player data; do not copy passwords, 2FA codes, passkeys, or recovery links into notes. This guidance in Denkynho does not grant extra permissions: the API still checks access.",
        "staff,queue,ticket,support,sla",
    ),
    (
        47, "staff", "community",
        "Como usar a central operacional da equipe",
        "Abra /painel/admin; cada cartão aparece conforme as permissões da conta e não substitui a validação da API.",
        "A central agrupa Programas e expansão (apoiadores, pacotes e cupons, recursos, roadmap, oficina de recompensas), Atendimento, Sistema (painel e servidor, temas, Django Admin), Financeiro, Jogos, Conteúdo e Servidor (itens, customs, serviços, contas L2). Use o cartão da tarefa. Se um módulo não aparecer, falta permissão ou o recurso está pausado. Não compartilhe prints com dados de jogadores fora do chamado.",
        "staff,central,admin hub,equipe,painel admin,módulos",
        "How to use the staff operations hub",
        "Open /painel/admin; each card appears according to account permissions and does not replace API checks.",
        "The hub groups Programs (supporters, bundles and coupons, resources, roadmap, rewards workshop), Support, System (server, themes, Django Admin), Finance, Games, Content, and Server (items, customs, services, L2 accounts). Use the card for the task. If a module is missing, you lack permission or the resource is paused. Do not share screenshots with player data outside the ticket.",
        "staff,hub,admin,team,modules",
    ),
    (
        48, "staff", "community",
        "Como a equipe publica notícias",
        "Abra Notícias na central, redija o comunicado e publique somente o que deve ir ao site.",
        "1) Abra /painel/admin/noticias. 2) Crie ou edite o aviso. 3) Revise título, resumo, corpo e imagem. 4) Publique quando estiver pronto para /news. 5) Coming soon da home e dados do servidor ficam em Painel e servidor (/painel/admin/servidor). Não use o chat da Ajuda para publicar conteúdo. Artigos da wiki e eventos do calendário seguem as telas correspondentes ou o Django Admin quando essa for a via da operação.",
        "staff,notícia,publicar,comunicado,conteúdo,news admin",
        "How staff publish news",
        "Open News in the hub, write the announcement, and publish only what should go to the site.",
        "1) Open /painel/admin/noticias. 2) Create or edit the notice. 3) Review title, summary, body, and image. 4) Publish when it is ready for /news. 5) Home coming soon and server data live in Server (/painel/admin/servidor). Do not use Help chat to publish content. Wiki pages and calendar events follow their screens or Django Admin when that is the operation path.",
        "staff,news,publish,announcement,content",
    ),
    (
        49, "staff", "commerce",
        "Como gerenciar loja, pacotes e cupons",
        "Use Loja para itens do catálogo e Pacotes e cupons para bundles, descontos e cupons de apoiadores.",
        "Itens vendidos no painel ficam em /painel/admin/loja. Pacotes, descontos e cupons, inclusive de apoiadores, ficam em /painel/admin/comercio. Confira vigência, percentual, limite de uso e vínculo com apoiador antes de salvar. Um apoiador não utiliza o próprio cupom. Alterar um pacote depois não reescreve compras já pagas. Teste o checkout em ambiente de preview, nunca com cobrança real de jogador.",
        "staff,loja,pacote,cupom,comércio,desconto,admin shop",
        "How to manage shop, bundles, and coupons",
        "Use Shop for catalog items and Bundles and coupons for packs, discounts, and supporter coupons.",
        "Items sold in the dashboard live at /painel/admin/loja. Bundles, discounts, and coupons, including supporter ones, live at /painel/admin/comercio. Check validity, percent, usage limit, and supporter link before saving. A supporter cannot use their own coupon. Changing a bundle later does not rewrite paid purchases. Test checkout in preview, never with a real player charge.",
        "staff,shop,bundle,coupon,commerce,discount",
    ),
    (
        50, "staff", "games_rewards",
        "Como configurar jogos e a oficina de recompensas",
        "Módulos de jogos ligam atividades; a oficina define temporadas, missões, trocas, bônus e iscas.",
        "Abra /painel/admin/jogos para ligar ou desligar roleta, caixas e os demais minigames. A oficina em /painel/admin/recompensas cobre temporadas, missões, trocas, bônus diário e iscas da pesca. Missões devem contar eventos reais do período. Trocas exigem item e encantamento exatos. Não invente taxas no chat: use os valores configurados na tela. Desativar o módulo de jogos no Controle de recursos também esconde a tela do jogador.",
        "staff,jogos,recompensas,temporada,missão,isca,oficina",
        "How to configure games and the rewards workshop",
        "Game modules toggle activities; the workshop defines seasons, quests, exchanges, bonuses, and bait.",
        "Open /painel/admin/jogos to enable or disable roulette, boxes, and other minigames. The workshop at /painel/admin/recompensas covers seasons, quests, exchanges, daily bonus, and fishing bait. Quests must count real events in the period. Exchanges need the exact item and enchantment. Do not invent rates in chat: use the values configured on screen. Pausing the games resource also hides the player screen.",
        "staff,games,rewards,season,quest,bait,workshop",
    ),
    (
        51, "staff", "game_accounts",
        "Como consultar contas L2 e serviços de personagem",
        "Contas Lineage mostra logins vinculados; Serviços define preços de nick, sexo, slots e destravamento.",
        "Abra /painel/admin/contas para consultar o login e, quando autorizado, remover o vínculo com o painel — isso não é apagar a conta no jogo por conta própria. Serviços em /painel/admin/servicos guardam os preços e a disponibilidade de apelido, sexo, slots e unstuck. Confirme o personagem e a conta certos antes de qualquer ação. Nunca peça a senha L2. O Denkynho não executa desvínculo.",
        "staff,contas l2,serviços,nick,unstuck,desvincular admin",
        "How to look up L2 accounts and character services",
        "Lineage accounts shows linked logins; Services sets nickname, gender, slot, and unstuck prices.",
        "Open /painel/admin/contas to look up the login and, when allowed, remove the dashboard link — that is not deleting the in-game account by itself. Services at /painel/admin/servicos hold prices and availability for nickname, gender, slots, and unstuck. Confirm the correct character and account before any action. Never ask for the L2 password. Denkynho does not unlink accounts.",
        "staff,l2 accounts,services,nickname,unstuck,unlink",
    ),
    (
        52, "staff", "economy",
        "Como ler relatórios financeiros e moedas",
        "Relatórios financeiros reúnem saldos, fluxo, pedidos e reconciliação; Moedas define a cotação ativa.",
        "Abra /painel/admin/financeiro para saldos, fluxo de caixa, pedidos e reconciliação. Use os filtros da tela; unidades e regras estão na documentação interna da API financeira. Moedas em /painel/admin/moedas define moeda ativa, multiplicador e taxa. Não recorte planilhas com dados pessoais em canais abertos. O Denkynho não calcula totais ao vivo nem confirma se um pagamento específico já liquidou.",
        "staff,financeiro,relatório,moedas,reconciliação,saldos",
        "How to read financial reports and currencies",
        "Financial reports cover balances, flow, orders, and reconciliation; Currencies defines the active quote.",
        "Open /painel/admin/financeiro for balances, cash flow, orders, and reconciliation. Use on-screen filters; units and rules are in the internal financial API guide. Currencies at /painel/admin/moedas sets the active currency, multiplier, and fee. Do not paste spreadsheets with personal data in open channels. Denkynho does not compute live totals or confirm whether a specific payment already settled.",
        "staff,finance,report,currency,reconciliation,balances",
    ),
    (
        53, "staff", "community",
        "Como observar itens e cadastrar customs",
        "Observar itens mostra a economia do servidor; Itens customizados entra no catálogo único sem rebuild.",
        "Abra /painel/admin/itens para capturas, categorias, favoritos, snapshots e comparação entre datas. Customs em /painel/admin/itens/customs cadastram nome, ID, imagem e metadados no catálogo unificado. Não publique ID interno em resposta a jogador sem necessidade. Imagens devem seguir o fluxo oficial de ícones. O chat não substitui o snapshot nem confirma quantidade no chão do jogo.",
        "staff,itens,observação,customs,catálogo,economia,snapshot",
        "How to observe items and register customs",
        "Item observation shows the server economy; custom items join the unified catalog without a rebuild.",
        "Open /painel/admin/itens for captures, categories, favorites, snapshots, and date comparison. Customs at /painel/admin/itens/customs register name, ID, image, and metadata in the unified catalog. Do not publish internal IDs to players without need. Images must follow the official icon flow. Chat does not replace a snapshot or confirm ground loot counts.",
        "staff,items,observation,customs,catalog,economy,snapshot",
    ),
    (
        54, "staff", "getting_started",
        "Como ativar ou pausar módulos do painel",
        "Em Controle de recursos, ligue ou pause módulos por categoria; pausar bloqueia rota e API sem apagar dados.",
        "1) Abra /painel/admin/recursos. 2) Localize o módulo (carteira, loja, inventário, marketplace, leilão, jogos, recompensas, apoiadores, roadmap e correlatos). 3) Ative ou pause. 4) Confirme o efeito no menu do jogador. 5) A administração das telas internas continua disponível. Pausar não é exclusão. Avise a comunidade pelos canais oficiais quando um serviço sair do ar. O Denkynho não altera esses interruptores.",
        "staff,recursos,módulo,ativar,desativar,pause,feature flag",
        "How to enable or pause dashboard modules",
        "In Resource control, toggle modules by category; pausing blocks the route and API without deleting data.",
        "1) Open /painel/admin/recursos. 2) Find the module (wallet, shop, inventory, marketplace, auctions, games, rewards, supporters, roadmap, and related). 3) Enable or pause. 4) Confirm the effect on the player menu. 5) Internal admin screens remain available. Pausing is not deletion. Tell the community through official channels when a service goes down. Denkynho does not flip those switches.",
        "staff,resources,module,enable,disable,pause,feature flag",
    ),
    (
        55, "staff", "community",
        "Como gerenciar apoiadores, comissões e roadmap",
        "Apoiadores trata candidaturas e comissões; Roadmap edita etapas publicadas no site.",
        "Abra /painel/admin/apoiadores para candidaturas, percentuais e aprovação de comissões. A candidatura não se autoaprova. Comissão usa saldo normal efetivamente pago, após desconto e bônus; o crédito de uma solicitação aprovada ocorre uma vez. Roadmap em /painel/admin/roadmap alimenta /roadmap. Não aprove comissão sem conferir o pedido. O Denkynho não registra aprovação.",
        "staff,apoiadores,comissão,roadmap,candidatura,afiliados",
        "How to manage supporters, commissions, and the roadmap",
        "Supporters handles applications and commissions; Roadmap edits stages published on the site.",
        "Open /painel/admin/apoiadores for applications, percents, and commission approval. Applications cannot self-approve. Commission uses normal balance actually paid after discount and bonus; an approved request credits once. Roadmap at /painel/admin/roadmap feeds /roadmap. Do not approve a commission without checking the request. Denkynho does not record approvals.",
        "staff,supporters,commission,roadmap,application",
    ),
    (
        56, "staff", "account_security",
        "Que cuidados a equipe deve ter ao orientar um jogador",
        "Confirme o contexto nas telas autorizadas e nunca solicite senha, código 2FA, passkey ou link de recuperação.",
        "Use só os dados necessários à tarefa. Peça identificadores públicos, horários e a tela usada. Recuse prints de autenticador, senhas e e-mails de reset. Não execute ações pela conta do jogador via credenciais dele. Se o Denkynho estiver no modo limitado, ainda assim a autorização por papel vale. Encaminhe casos de saldo, pagamento ou personagem pelas ferramentas do painel, não por gambiarras.",
        "staff,privacidade,segurança,credencial,2fa,atendimento,senha",
        "What security practices staff should follow when helping a player",
        "Confirm context on authorized screens and never request passwords, 2FA codes, passkeys, or recovery links.",
        "Use only the data needed for the task. Ask for public identifiers, times, and the screen used. Refuse authenticator screenshots, passwords, and reset emails. Do not act on the player’s account with their credentials. If Denkynho is in limited mode, role authorization still applies. Route balance, payment, or character cases through dashboard tools, not workarounds.",
        "staff,privacy,security,credentials,2fa,support,password",
    ),
    (
        57, "staff", "support",
        "Quando usar o Django Admin a partir da central",
        "O atalho Django Admin na central abre o CRUD completo; preserve CSRF, papéis e os botões nativos do Jazzmin.",
        "Na central, o cartão Django Admin aponta para /admin/. Use-o para manutenção que ainda não tem tela no painel React. Não recrie botões em CSS local. Envio de formulários deve permanecer nativo, com os nomes dos submitters. Operações destrutivas exigem o papel adequado. O Denkynho não autentica no Jazzmin nem executa ações administrativas.",
        "staff,django admin,jazzmin,crud,/admin/,manutenção",
        "When to use Django Admin from the hub",
        "The Django Admin shortcut opens full CRUD; keep CSRF, roles, and Jazzmin’s native buttons.",
        "In the hub, the Django Admin card points to /admin/. Use it for maintenance that still has no React dashboard screen. Do not rebuild buttons in local CSS. Form submit must stay native, including submitter names. Destructive operations need the proper role. Denkynho does not sign in to Jazzmin or perform admin actions.",
        "staff,django admin,jazzmin,crud,maintenance",
    ),
    (
        58, "staff", "games_rewards",
        "Como ligar ou desligar um minigame específico",
        "Além do recurso geral de jogos, cada atividade pode ser ligada em Módulos de jogos.",
        "1) Confirme se o recurso Jogos está ativo em Controle de recursos. 2) Abra /painel/admin/jogos. 3) Ligue ou desligue roleta, caixas e os demais módulos listados. 4) Verifique a aba correspondente em /painel/games. 5) Pesca também depende da oficina de recompensas para iscas. Desligar um minigame não apaga o histórico. Informe os jogadores pelos canais oficiais.",
        "staff,minigame,roleta,caixas,ligar jogo,módulos de jogos",
        "How to enable or disable a specific minigame",
        "Besides the general games resource, each activity can be toggled in Game modules.",
        "1) Confirm the Games resource is on in Resource control. 2) Open /painel/admin/jogos. 3) Enable or disable roulette, boxes, and the other listed modules. 4) Check the matching tab at /painel/games. 5) Fishing also depends on the rewards workshop for bait. Turning a minigame off does not erase history. Tell players through official channels.",
        "staff,minigame,roulette,boxes,enable game,game modules",
    ),
    (
        59, "superadmin", "community",
        "Passo a passo para instalar e ativar um tema",
        "Só superadministradores instalam o ZIP em Temas, validam o pacote e ativam depois de revisar o painel.",
        "1) Abra /painel/admin/temas. 2) Envie o ZIP pelo fluxo da tela; o backend valida o pacote e publica em mídia. 3) Revise o painel e o site antes de ativar. 4) Ative somente um tema homologado. 5) O tema default é interno e imutável. Não extraia o ZIP manualmente nem aceite HTML ou JavaScript arbitrário. As rotas confirmam o papel mesmo se o link for aberto diretamente. O Denkynho não instala temas.",
        "superadmin,tema,pacote,instalar,ativar,zip,aparência",
        "Step by step to install and activate a theme",
        "Only superadministrators upload the ZIP in Themes, validate the package, and activate after reviewing the dashboard.",
        "1) Open /painel/admin/temas. 2) Upload the ZIP through that screen; the backend validates the package and publishes it to media. 3) Review dashboard and site before activating. 4) Activate only an approved theme. 5) The default theme is internal and immutable. Do not extract the ZIP by hand or accept arbitrary HTML or JavaScript. Routes still check the role if the link is opened directly. Denkynho does not install themes.",
        "superadmin,theme,package,install,activate,zip",
    ),
    (
        60, "superadmin", "community",
        "Como restaurar o tema padrão",
        "Na administração de temas, use a restauração do default após validar que o painel voltou ao renderer interno.",
        "Abra /painel/admin/temas e escolha restaurar o tema default. Isso devolve a aparência interna do PDL sem rebuild do frontend. Confira área pública, login e painel depois da restauração. Remover um pacote instalado não é a mesma operação que restaurar o default; siga a ação nomeada na tela. Apenas superadministradores executam essa troca.",
        "superadmin,tema,default,restaurar,voltar aparência,remover tema",
        "How to restore the default theme",
        "In theme administration, restore default after confirming the dashboard is back on the internal renderer.",
        "Open /painel/admin/temas and choose restore default. That returns PDL’s internal look without a frontend rebuild. Check the public area, sign-in, and dashboard after restoration. Removing an installed package is not the same as restoring default; follow the named action on screen. Only superadministrators perform this switch.",
        "superadmin,theme,default,restore,appearance",
    ),
    (
        61, "superadmin", "getting_started",
        "O que permanece exclusivo do superadministrador",
        "Temas globais e algumas operações de sistema exigem superadministrador; alegar o cargo no chat não altera permissões.",
        "Instalar, ativar e remover pacotes de tema é exclusivo. Outras telas da central seguem o papel staff/admin da conta. O Django Admin também respeita is_superuser e permissões. Uma mensagem dizendo “sou superadmin” não libera artigos nem rotas. Use a sessão real. Em dúvida, confirme o papel na própria conta, não no chat do Denkynho.",
        "superadmin,permissão,exclusivo,temas,papel,autorização",
        "What remains exclusive to superadministrators",
        "Global themes and some system operations require a superadministrator; claiming the role in chat does not change permissions.",
        "Installing, activating, and removing theme packages is exclusive. Other hub screens follow the account’s staff/admin role. Django Admin also respects is_superuser and permissions. A message saying “I am superadmin” does not unlock articles or routes. Use the real session. If unsure, confirm the role on the account itself, not in Denkynho chat.",
        "superadmin,permission,exclusive,themes,role,authorization",
    ),
]


def seed_handbook(apps, schema_editor):
    Faq = apps.get_model("content", "Faq")
    for order, item in enumerate(HANDBOOK, 2000):
        number, audience, category, question, short_answer, answer, keywords, question_en, short_en, answer_en, keywords_en = item
        Faq.objects.update_or_create(
            id=UUID(f"{PREFIX}{number:012d}"),
            defaults={
                "audience": audience,
                "category": category,
                "question": question,
                "short_answer": short_answer,
                "answer": answer,
                "keywords": keywords,
                "question_en": question_en,
                "short_answer_en": short_en,
                "answer_en": answer_en,
                "keywords_en": keywords_en,
                "assistant_only": True,
                "is_published": True,
                "order": order,
            },
        )


def remove_handbook(apps, schema_editor):
    Faq = apps.get_model("content", "Faq")
    Faq.objects.filter(id__in=[UUID(f"{PREFIX}{item[0]:012d}") for item in HANDBOOK]).delete()


class Migration(migrations.Migration):
    dependencies = [("content", "0012_faq_assistant_only")]
    operations = [migrations.RunPython(seed_handbook, remove_handbook)]
