# Generated by Django 6.0.8 on 2026-09-04

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0013_seed_denkynho_handbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenkynhoProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identificador público. Sempre UUID v4.", unique=True)),
                ("seq_id", models.BigAutoField(editable=False, help_text="ID sequencial interno. Nunca expor via API.", primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("satiety", models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("energy", models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("happiness", models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("hygiene", models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("experience", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("last_decay_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="denkynho_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Perfil do Denkynho", "verbose_name_plural": "Perfis do Denkynho"},
        ),
        migrations.CreateModel(
            name="DenkynhoCareAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField()),
                ("action", models.CharField(choices=[("feed", "Alimentar"), ("sleep", "Dormir"), ("play", "Brincar"), ("care", "Dar carinho")], max_length=12)),
                ("xp_gained", models.PositiveSmallIntegerField(default=0)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="care_actions", to="content.denkynhoprofile")),
            ],
            options={"verbose_name": "Cuidado do Denkynho", "verbose_name_plural": "Cuidados do Denkynho"},
        ),
        migrations.AddConstraint(
            model_name="denkynhocareaction",
            constraint=models.UniqueConstraint(fields=("profile", "idempotency_key"), name="content_denkynho_care_idempotency"),
        ),
    ]
