# Generated by Django 6.0.8 on 2026-09-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_conversation_provider_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='denkynhoprofile',
            name='appearance',
            field=models.JSONField(blank=True, default=dict, help_text='Peças cosméticas liberadas e equipadas pelo usuário.'),
        ),
        migrations.AlterField(
            model_name='denkynhocareaction',
            name='action',
            field=models.CharField(choices=[('feed', 'Alimentar'), ('sleep', 'Dormir'), ('play', 'Brincar'), ('care', 'Dar carinho'), ('dance', 'Dançar juntos')], max_length=12),
        ),
    ]
