# Generated by Django 6.0.8 on 2026-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_denkynho_presence_and_handbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denkynhocareaction',
            name='action',
            field=models.CharField(choices=[('feed', 'Alimentar'), ('sleep', 'Dormir'), ('play', 'Brincar'), ('care', 'Dar carinho'), ('bath', 'Dar banho'), ('walk', 'Caminhar'), ('dance', 'Dançar juntos')], max_length=12),
        ),
    ]
