# Generated by Django 6.0.8 on 2026-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_add_denkynho_lake_scene_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords_es',
            field=models.CharField(blank=True, help_text='Términos alternativos en español separados por comas.', max_length=500),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='faq',
            name='short_answer_es',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_es',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='body_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_en',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_es',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_es',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
