# Generated by Django 6.0.8 on 2026-09-26 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_calendar_event_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Título (EN)')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='Título (ES)')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Badge / Etiqueta')),
                ('badge_en', models.CharField(blank=True, max_length=50, verbose_name='Badge (EN)')),
                ('badge_es', models.CharField(blank=True, max_length=50, verbose_name='Badge (ES)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, verbose_name='Descrição (EN)')),
                ('description_es', models.TextField(blank=True, verbose_name='Descrição (ES)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagem')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='URL Externa da Imagem (opcional)')),
                ('link', models.CharField(blank=True, default='', max_length=300, verbose_name='Link Principal (opcional)')),
                ('link_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Principal')),
                ('link_text_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Principal (EN)')),
                ('link_text_es', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Principal (ES)')),
                ('secondary_link', models.CharField(blank=True, default='', max_length=300, verbose_name='Link Secundário (opcional)')),
                ('secondary_link_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Secundário')),
                ('secondary_link_text_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Secundário (EN)')),
                ('secondary_link_text_es', models.CharField(blank=True, default='', max_length=100, verbose_name='Texto do Botão Secundário (ES)')),
                ('display_type', models.CharField(choices=[('popup', 'Modal Pop-up (Rico)'), ('visual', 'Banner Visual (Flyer)')], default='popup', max_length=20, verbose_name='Formato de Exibição')),
                ('target_location', models.CharField(choices=[('all', 'Todas as páginas públicas'), ('landing', 'Apenas Landing Page'), ('coming_soon', 'Apenas Coming Soon'), ('landing_and_coming_soon', 'Landing Page e Coming Soon'), ('panel', 'Painel do Jogador')], default='landing_and_coming_soon', max_length=30, verbose_name='Onde Exibir')),
                ('dismiss_policy', models.CharField(choices=[('session', '1 vez por sessão'), ('always', 'Sempre exibir'), ('days', 'Não exibir novamente por X dias'), ('dismiss_forever', 'Não exibir mais após fechar')], default='days', max_length=20, verbose_name='Controle de Frequência')),
                ('dismiss_days', models.PositiveIntegerField(default=7, help_text='Usado quando a frequência é configurada para X dias.', verbose_name='Dias sem reexibir')),
                ('auto_close', models.BooleanField(default=False, verbose_name='Fechar automaticamente')),
                ('auto_close_delay', models.PositiveIntegerField(default=10, verbose_name='Tempo para fechar (segundos)')),
                ('show_close_button', models.BooleanField(default=True, verbose_name='Exibir botão de fechar')),
                ('width_px', models.PositiveIntegerField(blank=True, default=640, null=True, verbose_name='Largura máxima (px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de prioridade')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'target_location', 'order'], name='content_ban_is_acti_77ddaa_idx'), models.Index(fields=['start_date', 'end_date'], name='content_ban_start_d_85efb8_idx')],
            },
        ),
    ]
