# Generated by Django 6.0.8 on 2026-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_seed_panel_site_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapentry',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapentry',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapentry',
            name='title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='roadmapentry',
            name='title_es',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
