# Generated by Django 6.0.8 on 2026-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_add_spanish_and_cms_i18n_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Comissão', 'verbose_name_plural': 'Comissões'},
        ),
        migrations.AlterModelOptions(
            name='commissionpayout',
            options={'verbose_name': 'Repasse de comissão', 'verbose_name_plural': 'Repasses de comissão'},
        ),
        migrations.AlterModelOptions(
            name='roadmapentry',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Entrada do roadmap', 'verbose_name_plural': 'Entradas do roadmap'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'verbose_name': 'Apoiador', 'verbose_name_plural': 'Apoiadores'},
        ),
        migrations.AlterModelOptions(
            name='systemresource',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Recurso do sistema', 'verbose_name_plural': 'Recursos do sistema'},
        ),
    ]
