# Generated by Django 6.0.8 on 2026-09-02 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='shoppurchase',
            options={},
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cart',
            name='use_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='bonus_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='items_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='request_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='shoppurchase',
            constraint=models.UniqueConstraint(fields=('user', 'request_key'), name='shop_checkout_idempotency'),
        ),
        migrations.AddField(
            model_name='cartpackage',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shop.cart'),
        ),
        migrations.AddField(
            model_name='cartpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoppackage'),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.supporter'),
        ),
        migrations.AddConstraint(
            model_name='cartpackage',
            constraint=models.UniqueConstraint(fields=('cart', 'package'), name='cart_unique_package'),
        ),
    ]
