# Generated by Django 6.0.8 on 2026-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartpackage_promotioncode_alter_shoppurchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AlterModelOptions(
            name='cartpackage',
            options={'verbose_name': 'Pacote do carrinho', 'verbose_name_plural': 'Pacotes do carrinho'},
        ),
        migrations.AlterModelOptions(
            name='promotioncode',
            options={'verbose_name': 'Código promocional', 'verbose_name_plural': 'Códigos promocionais'},
        ),
        migrations.AlterModelOptions(
            name='shoppackageitem',
            options={'verbose_name': 'Item do pacote', 'verbose_name_plural': 'Itens do pacote'},
        ),
        migrations.AlterModelOptions(
            name='shoppurchase',
            options={'verbose_name': 'Compra da loja', 'verbose_name_plural': 'Compras da loja'},
        ),
    ]
