# Generated by Django 6.0.8 on 2026-09-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indexconfig",
            options={
                "verbose_name": "Configuração do painel",
                "verbose_name_plural": "Configurações do painel",
            },
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="chronicle",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="coming_soon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="enchant",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="max_level",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="rates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="indexconfig",
            name="staff_only_login",
            field=models.BooleanField(default=False),
        ),
    ]
