# Generated by Django 6.0.8 on 2026-09-02 00:15

import apps.server.infrastructure.item_observation_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_panel_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemObservationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('item_ids', models.JSONField(blank=True, default=list, help_text='Exemplo: [57, 4037]. Em sobreposições, vale a primeira categoria na ordem.', validators=[apps.server.infrastructure.item_observation_models.validate_item_ids], verbose_name='IDs dos itens')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de observação',
                'verbose_name_plural': 'Categorias de observação',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemObservationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(verbose_name='Data')),
                ('source', models.CharField(max_length=255, verbose_name='Origem L2')),
                ('total_characters', models.PositiveBigIntegerField(default=0, verbose_name='Personagens')),
                ('total_instances', models.PositiveBigIntegerField(default=0, verbose_name='Stacks L2')),
                ('total_quantity', models.DecimalField(decimal_places=0, default=0, max_digits=30, verbose_name='Quantidade L2')),
                ('site_quantity', models.DecimalField(decimal_places=0, default=0, max_digits=30, verbose_name='Quantidade no painel')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Snapshot de itens',
                'verbose_name_plural': 'Snapshots de itens',
                'ordering': ['-snapshot_date', '-created_at'],
                'permissions': [('capture_itemobservationsnapshot', 'Pode capturar snapshot dos itens L2')],
            },
        ),
        migrations.CreateModel(
            name='ItemObservationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=24)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=30)),
                ('instances', models.PositiveBigIntegerField()),
                ('unique_owners', models.PositiveBigIntegerField()),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='server.itemobservationsnapshot')),
            ],
            options={
                'ordering': ['-quantity', 'item_id', 'location'],
            },
        ),
        migrations.CreateModel(
            name='ItemObservationFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=255)),
                ('item_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'item_id'), name='unique_item_favorite')],
            },
        ),
        migrations.AddConstraint(
            model_name='itemobservationsnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'snapshot_date'), name='unique_item_snapshot_day'),
        ),
        migrations.AddConstraint(
            model_name='itemobservationdetail',
            constraint=models.UniqueConstraint(fields=('snapshot', 'item_id', 'location'), name='unique_item_snapshot_location'),
        ),
    ]
