# Generated by Django 6.0.8 on 2026-09-02 01:25

import apps.server.infrastructure.custom_item_models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_itemobservationcategory_itemobservationsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='ID no jogo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(upload_to=apps.server.infrastructure.custom_item_models.custom_item_image_path, verbose_name='Imagem')),
                ('category', models.CharField(choices=[('COMUM', 'Comum'), ('WEAPON', 'Arma'), ('SHIELD', 'Escudo'), ('HELMET', 'Elmo'), ('ARMOR', 'Armadura'), ('PANTS', 'Calça'), ('BOOTS', 'Botas'), ('GLOVES', 'Luvas'), ('NECKLACE', 'Colar'), ('EARRING', 'Brinco'), ('RING', 'Anel'), ('HAIR', 'Acessório'), ('FACE', 'Máscara'), ('UNDERWEAR', 'Roupa íntima'), ('FORMAL', 'Traje'), ('PET', 'Pet')], default='COMUM', max_length=24, verbose_name='Tipo')),
                ('grade', models.CharField(choices=[('NG', 'NG'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='NG', max_length=2, verbose_name='Grau')),
                ('tradeable', models.BooleanField(default=True, verbose_name='Negociável')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.server.infrastructure.custom_item_models.validate_custom_metadata], verbose_name='Metadados públicos')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item customizado',
                'verbose_name_plural': 'Itens customizados',
                'ordering': ['item_id'],
            },
        ),
    ]
