# Generated by Django 6.0.8 on 2026-09-04 22:45

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("server", "0004_custom_catalog_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="CharacterServiceOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador público. Sempre UUID v4.",
                        unique=True,
                    ),
                ),
                (
                    "seq_id",
                    models.BigAutoField(
                        editable=False,
                        help_text="ID sequencial interno. Nunca expor via API.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("login", models.CharField(max_length=45)),
                ("character_id", models.PositiveIntegerField()),
                ("service", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("completed", "Concluído"),
                            ("rejected", "Estornado"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação de serviço",
                "verbose_name_plural": "Operações de serviço",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "request_key"), name="pdl_character_service_key"
                    )
                ],
            },
        ),
    ]
