# Generated by Django 6.0.8 on 2026-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_indexconfig_coming_soon_launch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemobservationdetail',
            options={'ordering': ['-quantity', 'item_id', 'location'], 'verbose_name': 'Detalhe de observação', 'verbose_name_plural': 'Detalhes de observação'},
        ),
        migrations.AlterModelOptions(
            name='itemobservationfavorite',
            options={'verbose_name': 'Favorito de observação', 'verbose_name_plural': 'Favoritos de observação'},
        ),
    ]
