# Generated by Django 6.0.8 on 2026-09-17 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tavern_service_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterJailState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('char_id', models.PositiveIntegerField(unique=True, verbose_name='ID do personagem')),
                ('login', models.CharField(db_index=True, max_length=45, verbose_name='Login')),
                ('char_name', models.CharField(max_length=35, verbose_name='Personagem')),
                ('jailed', models.BooleanField(db_index=True, default=True, verbose_name='Preso')),
                ('jail_until', models.DateTimeField(blank=True, null=True, verbose_name='Preso até')),
                ('jail_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Prisão do personagem',
                'verbose_name_plural': 'Prisões de personagens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_username', models.CharField(max_length=150, verbose_name='Usuário da equipe')),
                ('action', models.CharField(db_index=True, max_length=20, verbose_name='Ação')),
                ('char_id', models.PositiveIntegerField(db_index=True, verbose_name='ID do personagem')),
                ('char_name', models.CharField(max_length=35, verbose_name='Personagem')),
                ('login', models.CharField(db_index=True, max_length=45, verbose_name='Login')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('was_online', models.BooleanField(default=False, verbose_name='Estava online')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Ação de moderação',
                'verbose_name_plural': 'Ações de moderação',
                'ordering': ['-created_at'],
            },
        ),
    ]
