# Generated by Django 6.0.8 on 2026-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_indexconfig_access_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfig',
            name='character_creation',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuração inicial de personagens'),
        ),
    ]
