# Generated by Django 6.0.8 on 2026-10-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_indexconfig_character_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfig',
            name='unstuck_location',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Destino de destravamento'),
        ),
    ]
