# Generated by Django 6.0.8 on 2026-09-11 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_options_auction_character_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='char_clan_name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_class',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_is_clan_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_name',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_pk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_pvp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_sex',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='char_title',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='auction',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auction',
            name='kind',
            field=models.CharField(choices=[('item', 'Item'), ('character', 'Personagem')], default='item', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='old_account',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='bid',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['kind', 'status'], name='auction_auc_kind_81dd40_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['char_id', 'status'], name='auction_auc_char_id_0f10e4_idx'),
        ),
    ]
