# Generated by Django 6.0.8 on 2026-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_character_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bag_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
