# Generated by Django 6.0.8 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0004_auction_bag_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="Skills do personagem"),
        ),
    ]
