# Generated by Django 6.0.8 on 2026-10-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_impersonationsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('support_view', 'Consultar chamados'), ('support_manage', 'Gerenciar chamados'), ('moderation_view', 'Consultar moderação'), ('moderation_manage', 'Gerenciar moderação'), ('accounts_view', 'Consultar contas de jogo'), ('accounts_manage', 'Gerenciar contas de jogo'), ('content_view', 'Consultar conteúdo editorial'), ('content_manage', 'Gerenciar conteúdo editorial'), ('games_view', 'Consultar jogos e recompensas'), ('games_manage', 'Gerenciar jogos e recompensas'), ('commerce_view', 'Consultar comércio'), ('commerce_manage', 'Gerenciar comércio'), ('finance_view', 'Consultar configuração financeira'), ('finance_manage', 'Gerenciar configuração financeira'), ('programs_view', 'Consultar apoiadores e repasses'), ('programs_manage', 'Gerenciar apoiadores e repasses'), ('resources_view', 'Consultar disponibilidade de recursos'), ('resources_manage', 'Gerenciar disponibilidade de recursos'), ('settings_view', 'Consultar configurações do painel'), ('settings_manage', 'Gerenciar configurações do painel'), ('notifications_view', 'Consultar avisos'), ('notifications_manage', 'Gerenciar avisos'), ('operational_reports_view', 'Consultar relatórios operacionais'), ('operational_reports_manage', 'Gerenciar relatórios operacionais'), ('financial_reports_view', 'Consultar relatórios financeiros'), ('financial_reports_manage', 'Gerenciar relatórios financeiros'), ('audit_view', 'Consultar auditoria'), ('audit_manage', 'Gerenciar auditoria'), ('metrics_view', 'Consultar métricas'), ('metrics_manage', 'Gerenciar métricas'), ('items_view', 'Consultar observação e catálogo de itens'), ('items_manage', 'Gerenciar observação e catálogo de itens'), ('docs_view', 'Consultar documentação da API'), ('docs_manage', 'Gerenciar documentação da API')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Jogador'), ('supporter', 'Apoiador'), ('promoter', 'Divulgador'), ('partner', 'Parceiro'), ('support', 'Suporte'), ('editor', 'Editor'), ('moderator', 'Moderador'), ('staff', 'Equipe'), ('admin', 'Administrador')], default='player', max_length=16),
        ),
    ]
