# Generated by Django 6.0.8 on 2026-08-31 18:18

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_coinpurchasebonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('coins', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_brl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pacote de moedas',
                'verbose_name_plural': 'Pacotes de moedas',
                'ordering': ['sort_order', 'coins'],
            },
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='usd_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8),
        ),
    ]
