# Generated by Django 6.0.8 on 2026-09-02 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_seed_coin_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_key', models.UUIDField()),
                ('direction', models.CharField(choices=[('to_game', 'Enviar ao jogo'), ('from_game', 'Retirar do jogo')], max_length=10)),
                ('login', models.CharField(max_length=45)),
                ('character_id', models.PositiveIntegerField()),
                ('character_name', models.CharField(max_length=100)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='unique_game_exchange_request')],
            },
        ),
    ]
