# Generated by Django 6.0.8 on 2026-09-08 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_gameexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPurchasePromo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoção de recarga',
                'verbose_name_plural': 'Promoções de recarga',
                'ordering': ['-updated_at'],
            },
        ),
    ]
