# Generated by Django 6.0.8 on 2026-09-27 21:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_coinpurchasepromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpurchasepromo',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='coinpurchasepromo',
            name='first_purchase_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinpurchasepromo',
            name='first_purchase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='coinpurchasepromo',
            name='pix_bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='coinpurchasepromo',
            name='stacking_mode',
            field=models.CharField(choices=[('max', 'Maior bônus'), ('sum', 'Cumulativo')], default='max', max_length=20),
        ),
    ]
