# Generated by Django 6.0.8 on 2026-08-31 16:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('item_id', models.PositiveIntegerField(default=0)),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('rarity', models.CharField(default='comum', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prêmio da roleta',
                'verbose_name_plural': 'Prêmios da roleta',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_bag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed', models.BooleanField(default=False)),
                ('seed', models.BigIntegerField(default=0)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giro da roleta',
                'verbose_name_plural': 'Giros da roleta',
            },
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.bag')),
            ],
            options={
                'verbose_name': 'Item da bag',
                'unique_together': {('bag', 'item_id', 'enchant')},
            },
        ),
        migrations.CreateModel(
            name='DailyBonusClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bonus_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resgate de bônus diário',
                'unique_together': {('user', 'claimed_on')},
            },
        ),
    ]
