# Generated by Django 6.0.8 on 2026-08-31 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_seed_game_configs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('boosters_amount', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de caixa',
                'verbose_name_plural': 'Tipos de caixa',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('item_id', models.PositiveIntegerField()),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item de catálogo',
                'verbose_name_plural': 'Itens de catálogo',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_boxes', to=settings.AUTH_USER_MODEL)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='games.boxtype')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='BoxSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=120)),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('probability', models.PositiveIntegerField(default=1)),
                ('opened', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='games.box')),
            ],
            options={
                'verbose_name': 'Booster da caixa',
            },
        ),
        migrations.AddField(
            model_name='boxtype',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='box_types', to='games.catalogitem'),
        ),
        migrations.CreateModel(
            name='DiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet_type', models.CharField(max_length=20)),
                ('bet_amount', models.PositiveIntegerField()),
                ('roll', models.PositiveIntegerField()),
                ('won', models.BooleanField(default=False)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogada de dados',
            },
        ),
        migrations.CreateModel(
            name='SlotHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reels', models.JSONField(default=list)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giro de slots',
            },
        ),
    ]
