# Generated by Django 6.0.8 on 2026-08-31 17:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_seed_minigames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField()),
                ('required_xp', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nível do passe',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='BattlePassSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('premium_price', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Temporada do passe',
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('min_rod_level', models.PositiveIntegerField(default=1)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('fichas_reward', models.PositiveIntegerField(default=0)),
                ('item_id', models.PositiveIntegerField(default=0)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Peixe',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveIntegerField(default=1)),
                ('required_weapon_level', models.PositiveIntegerField(default=0)),
                ('fragment_reward', models.PositiveIntegerField(default=3)),
                ('hp', models.PositiveIntegerField(default=40)),
                ('attack', models.PositiveIntegerField(default=8)),
                ('defense', models.PositiveIntegerField(default=2)),
                ('respawn_seconds', models.PositiveIntegerField(default=30)),
                ('defeated_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Monstro',
            },
        ),
        migrations.CreateModel(
            name='BattlePassReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('item_id', models.PositiveIntegerField(default=57)),
                ('item_name', models.CharField(default='Adena', max_length=120)),
                ('enchant', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('level_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='games.battlepasslevel')),
            ],
            options={
                'verbose_name': 'Recompensa do passe',
            },
        ),
        migrations.AddField(
            model_name='battlepasslevel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='games.battlepassseason'),
        ),
        migrations.CreateModel(
            name='EconomyWeapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('fragments', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy_weapon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arma da economia',
            },
        ),
        migrations.CreateModel(
            name='FishingCatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=False)),
                ('rod_level', models.PositiveIntegerField(default=1)),
                ('fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.fish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_catches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pescaria',
            },
        ),
        migrations.CreateModel(
            name='FishingRod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_rod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vara de pesca',
            },
        ),
        migrations.CreateModel(
            name='EconomyFightLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('won', models.BooleanField(default=False)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('fragments_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_fights', to=settings.AUTH_USER_MODEL)),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.monster')),
            ],
            options={
                'verbose_name': 'Combate da economia',
            },
        ),
        migrations.AlterUniqueTogether(
            name='battlepasslevel',
            unique_together={('season', 'level')},
        ),
        migrations.CreateModel(
            name='UserBattlePassClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='games.battlepassreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_pass_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resgate do passe',
                'unique_together': {('user', 'reward')},
            },
        ),
        migrations.CreateModel(
            name='UserBattlePassProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público. Sempre UUID v4.', unique=True)),
                ('seq_id', models.BigAutoField(editable=False, help_text='ID sequencial interno. Nunca expor via API.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('has_premium', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='games.battlepassseason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do passe',
                'unique_together': {('user', 'season')},
            },
        ),
    ]
