# Generated by Django 6.0.8 on 2026-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_dailybonusseason_fishingbait_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlepassexchange',
            options={'verbose_name': 'Troca do passe', 'verbose_name_plural': 'Trocas do passe'},
        ),
        migrations.AlterModelOptions(
            name='battlepassmilestone',
            options={'verbose_name': 'Marco do passe', 'verbose_name_plural': 'Marcos do passe'},
        ),
        migrations.AlterModelOptions(
            name='battlepassquest',
            options={'verbose_name': 'Missão do passe', 'verbose_name_plural': 'Missões do passe'},
        ),
        migrations.AlterModelOptions(
            name='battlepassquestclaim',
            options={'verbose_name': 'Resgate de missão do passe', 'verbose_name_plural': 'Resgates de missão do passe'},
        ),
        migrations.AlterModelOptions(
            name='dailybonusday',
            options={'ordering': ['day'], 'verbose_name': 'Dia de bônus diário', 'verbose_name_plural': 'Dias de bônus diário'},
        ),
        migrations.AlterModelOptions(
            name='dailybonuspoolentry',
            options={'verbose_name': 'Entrada do pool de bônus', 'verbose_name_plural': 'Entradas do pool de bônus'},
        ),
        migrations.AlterModelOptions(
            name='dailybonusseason',
            options={'verbose_name': 'Temporada de bônus diário', 'verbose_name_plural': 'Temporadas de bônus diário'},
        ),
        migrations.AlterModelOptions(
            name='fishingbait',
            options={'verbose_name': 'Isca de pesca', 'verbose_name_plural': 'Iscas de pesca'},
        ),
        migrations.AlterModelOptions(
            name='gamerewardlog',
            options={'verbose_name': 'Log de recompensa de jogo', 'verbose_name_plural': 'Logs de recompensa de jogo'},
        ),
        migrations.AlterModelOptions(
            name='userfishingbait',
            options={'verbose_name': 'Isca do jogador', 'verbose_name_plural': 'Iscas do jogador'},
        ),
    ]
