# Generated by Django 6.0.8 on 2026-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_seed_arena_monsters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtype',
            name='boosters_amount',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
