# Generated by Django 5.2
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.support.models
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identificador público. Sempre UUID v4.", unique=True)),
                ("seq_id", models.BigAutoField(editable=False, help_text="ID sequencial interno. Nunca expor via API.", primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("protocol", models.CharField(default=apps.support.models.make_protocol, editable=False, max_length=24, unique=True)),
                ("subject", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("category", models.CharField(choices=[("technical", "Problema técnico"), ("billing", "Pagamento e loja"), ("account", "Conta e segurança"), ("game", "Suporte ao jogo"), ("bug", "Relatar um bug"), ("report", "Denúncia"), ("suggestion", "Sugestão"), ("other", "Outro assunto")], default="other", max_length=24)),
                ("priority", models.CharField(choices=[("low", "Baixa"), ("normal", "Normal"), ("high", "Alta"), ("urgent", "Urgente")], default="normal", max_length=12)),
                ("status", models.CharField(choices=[("open", "Aberto"), ("in_progress", "Em atendimento"), ("waiting_user", "Aguardando jogador"), ("waiting_team", "Aguardando equipe"), ("resolved", "Resolvido"), ("closed", "Fechado")], db_index=True, default="open", max_length=20)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_support_tickets", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="support_tickets", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Chamado", "verbose_name_plural": "Chamados", "ordering": ["-last_activity_at"]},
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identificador público. Sempre UUID v4.", unique=True)),
                ("seq_id", models.BigAutoField(editable=False, help_text="ID sequencial interno. Nunca expor via API.", primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_staff_reply", models.BooleanField(default=False)),
                ("is_internal", models.BooleanField(default=False)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="support.ticket")),
            ],
            options={"verbose_name": "Mensagem do chamado", "verbose_name_plural": "Mensagens dos chamados", "ordering": ["created_at"]},
        ),
        migrations.AddIndex(model_name="ticket", index=models.Index(fields=["user", "status"], name="pdl_ticket_user_status")),
        migrations.AddIndex(model_name="ticket", index=models.Index(fields=["status", "priority"], name="pdl_ticket_queue")),
    ]
