import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Plus, Pencil, Trash2 } from 'lucide-react'
import { commerceApi, type Promo, type ShopPackage } from '../../services/domain/commerce.service'
import { programsApi } from '../../services/domain/programs.service'
import { shopApi } from '../../services/api'
import { Empty, ErrorNotice, Loading, Status } from '../../components/programs/ProgramUI'
import { useProgramAction } from '../../components/programs/useProgramAction'
import { AdminHeader } from './AdminChrome'

export function AdminCommercePage() {
  const packs=useQuery({queryKey:['staff-packages'],queryFn:commerceApi.staffPackages})
  const promos=useQuery({queryKey:['staff-promos'],queryFn:commerceApi.staffPromos})
  const items=useQuery({queryKey:['shop'],queryFn:shopApi.catalog})
  const supporters=useQuery({queryKey:['staff-supporters'],queryFn:programsApi.staffSupporters})
  const action=useProgramAction()
  const [tab,setTab]=useState('packages')
  const [draft,setDraft]=useState<Partial<ShopPackage & Promo>|null>(null)
  const [contents,setContents]=useState<{item:string;quantity:number}[]>([])
  function open(row?:ShopPackage|Promo) {setDraft(row||{});setContents(row&&'contents'in row?row.contents.map(c=>({item:c.item,quantity:c.quantity})):[])}
  return <div className="program-page"><AdminHeader kicker="Economia" title="Pacotes e cupons" description="Monte combinações de itens, configure descontos e vincule cupons aos apoiadores aprovados."/><ErrorNotice error={packs.error||promos.error||action.error}/><div className="program-tabs">{[['packages','Pacotes'],['promos','Cupons']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setDraft(null)}}>{label}</button>)}</div><div className="program-actions"><button className="btn" onClick={()=>open()}><Plus size={18}/>Criar {tab==='packages'?'pacote':'cupom'}</button></div>
    {draft&&<section className="card program-section"><h2>{draft.id?'Editar':'Novo'} {tab==='packages'?'pacote':'cupom'}</h2><form key={draft.id||tab} className="program-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const data=tab==='packages'?{name:f.get('name'),total_price:f.get('total_price'),active:f.has('active'),items:contents}:{code:f.get('code'),percent:f.get('percent'),active:f.has('active'),starts_at:f.get('starts_at')?new Date(String(f.get('starts_at'))).toISOString():null,ends_at:f.get('ends_at')?new Date(String(f.get('ends_at'))).toISOString():null,max_uses:Number(f.get('max_uses')),supporter:f.get('supporter')||null};void action.run(()=>commerceApi.save(tab,data,draft.id)).then(ok=>{if(ok)setDraft(null)})}}>
      {tab==='packages'?<><div className="program-fields"><label>Nome do pacote<input name="name" required defaultValue={draft.name}/></label><label>Preço em moedas<input name="total_price" type="number" min={0} step="0.01" required defaultValue={draft.total_price}/></label></div><h3>Conteúdo do pacote</h3>{contents.map((c,i)=><div className="program-fields" key={i}><label>Item<select required value={c.item} onChange={e=>setContents(contents.map((r,j)=>j===i?{...r,item:e.target.value}:r))}><option value="">Selecione um item</option>{items.data?.map(item=><option key={item.id} value={item.id}>{item.name} · {item.quantity} unidades</option>)}</select></label><label>Quantidade<input type="number" min={1} required value={c.quantity} onChange={e=>setContents(contents.map((r,j)=>j===i?{...r,quantity:Number(e.target.value)}:r))}/></label><button className="btn ghost" type="button" onClick={()=>setContents(contents.filter((_,j)=>i!==j))}><Trash2 size={14}/>Remover item</button></div>)}<div className="program-actions"><button className="btn ghost" type="button" onClick={()=>setContents([...contents,{item:'',quantity:1}])}><Plus size={16}/>Adicionar item</button></div></>:<div className="program-fields"><label>Código<input name="code" required maxLength={40} defaultValue={draft.code}/></label><label>Desconto (%)<input name="percent" type="number" min={0} max={100} step="0.01" required defaultValue={draft.percent||10}/></label><label>Início (opcional)<input type="datetime-local" name="starts_at" defaultValue={dateValue(draft.starts_at)}/></label><label>Fim (opcional)<input type="datetime-local" name="ends_at" defaultValue={dateValue(draft.ends_at)}/></label><label>Limite de usos (0 = ilimitado)<input name="max_uses" type="number" min={0} defaultValue={draft.max_uses||0}/></label><label>Apoiador<select name="supporter" defaultValue={draft.supporter||''}><option value="">Sem apoiador</option>{supporters.data?.supporters.filter(s=>s.status==='approved').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>}
      <label className="program-check"><input name="active" type="checkbox" defaultChecked={draft.active??true}/>Ativo</label><div className="program-actions"><button className="btn" disabled={action.busy||tab==='packages'&&!contents.length}>Salvar</button><button type="button" className="btn ghost" onClick={()=>setDraft(null)}>Cancelar</button></div></form></section>}
    {(packs.isPending||promos.isPending)&&<Loading/>}<div className="program-grid">{tab==='packages'?packs.data?.map(p=><article className="card program-section" key={p.id}><div className="program-section-heading"><h2>{p.name}</h2><Status value={p.active?'available':'rejected'}/></div><strong>{p.total_price} moedas</strong>{p.contents.map((c,i)=><small className="muted" key={i}>{c.grant_quantity} × {c.name}</small>)}<div className="program-actions"><button className="btn ghost" onClick={()=>open(p)}><Pencil size={16}/>Editar pacote</button></div></article>):promos.data?.map(p=><article className="card program-section" key={p.id}><div className="program-section-heading"><h2>{p.code}</h2><Status value={p.active?'available':'rejected'}/></div><strong>{p.percent}% de desconto</strong><small className="muted">{p.uses} utilizações · Limite {p.max_uses||'ilimitado'}</small><div className="program-actions"><button className="btn ghost" onClick={()=>open(p)}><Pencil size={16}/>Editar cupom</button></div></article>)}</div>{(tab==='packages'?packs.data:promos.data)?.length===0&&<Empty>Nenhum registro nesta seção.</Empty>}
  </div>
}
function dateValue(value?:string|null) {if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
